#ifndef RTE_RTE_FREERTOS_TRACE_FMT_H
#define RTE_RTE_FREERTOS_TRACE_FMT_H

/*--------------------------------------------------------------*/
/* @file    rte_FreeRTOS_trace_fmt.h                            */
/* @author  Branko Premzel                                      */
/* @brief   RTEdbg format definitions for the FreeRTOS trace.   */
/*                                                              */
/* SPDX-License-Identifier: MIT                                 */
/*--------------------------------------------------------------*/

/*----------------------------------------------------------------------------------*/
/*      Printf strings for the trace macros defined in "rte_FreeRTOS_trace.h"       */
/*                                                                                  */
/* The RTEmsg utility generates several distinct log files for specialized analysis */
/* during binary log file decoding:                                                 */
/*  # Main.log: Contains general information about all logged messages generated by */
/*    the application.                                                              */
/*  # RTOS_main.log: Includes all messages specifically logged using the FreeRTOS   */
/*    trace macros.                                                                 */
/*  # RTOS_tasks.log: Records the execution times and activity data for all FreeRTOS*/
/*    tasks.                                                                        */
/*  # RTOS_errors.log: Stores all messages that report FreeRTOS detected errors.    */
/*    This file captures messages from FreeRTOS trace macros containing the keyword */
/*    FAILED in their name.                                                         */
/*  # RTOS_timing.vcd: Timing information is exported separately to a VCD (Value    */
/*    Change Dump) file. This standard format allows the data to be visualized and  */
/*    analyzed graphically using common VCD viewers, such as GTKWave.               */
/* Note: Programmers are free to log other related information into the specified   */
/* files as needed.                                                                 */
/*----------------------------------------------------------------------------------*/

/*--------------- Define the FreeRTOS log files ----------------*/
// OUT_FILE(RTOS_MAIN, "RTOS_main.log", "w", "FreeRTOS event trace\nNote: The name Queue can also mean a semaphore or a mutex, since the mechanism of queues is used for all of them.\n\nMSG #     Time\n- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n")
// OUT_FILE(RTOS_ERRORS, "RTOS_errors.log", "w", "Errors Reported During FreeRTOS Execution\n\n")
// OUT_FILE(RTOS_TASKS, "RTOS_tasks.log", "w", "Execution times of FreeRTOS tasks, including time spent in the RTOS kernel, ISRs, and exception handlers.\n\nMSG #  Time[ms] Task name Run time [ms]\n- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n")
// OUT_FILE(RTOS_TIMING, "RTOS_timing.vcd", "w")

/*-------------- Define the message filter names ---------------*/
/* An individual filter definition can be deleted (or commented), freeing up the filter */
/* number for other purposes. When a filter is deleted, it is replaced with F_RTOS_BASIC. */
/* The F_RTOS_BASIC filter must not be disabled. */
// FILTER(F_RTOS_BASIC,   "FreeRTOS Basic task, queue and notifications trace")
// FILTER(F_RTOS_TASKS,   "FreeRTOS Additional Task and Notification trace")
// FILTER(F_RTOS_MALLOC,  "FreeRTOS Malloc and Free")
// FILTER(F_RTOS_TIMER,   "FreeRTOS Timer")
// FILTER(F_RTOS_QUEUE,   "FreeRTOS Addditional Queue, Semaphore and Mutex trace")
// FILTER(F_RTOS_STREAMS, "FreeRTOS Streams")
// FILTER(F_RTOS_EXPERT,  "FreeRTOS Expert")

/* Keep track of the last task's name to display its execution time when the next task begins. */
// MEMO(M_LAST_TASK_NAME)

// MSG1_RTOS_TASK_SWITCHED_IN
// >RTOS_TIMING "s _PreviousTaskTime_ms=%[T](*1000.).4f"
// >RTOS_TASKS "%N %t Task%[M_LAST_TASK_NAME]4s %[T](*1000)7.4f\n"
// >RTOS_TIMING "b Task%[M_LAST_TASK_NAME]s=0"
// >RTOS_TIMING "s _Task_name=%[0:32s]s"
// >RTOS_TIMING "b Task%[0:32s]s=1"
// >>RTOS_MAIN "%N %t Task%[M_LAST_TASK_NAME]4s ran for %[T](*1000.).4f ms.\n           "
// >>RTOS_MAIN ">>>> Task%[0:32u]<M_LAST_TASK_NAME>s switched in. <<<<\n"
// >RTOS_TIMING "f Task%[M_LAST_TASK_NAME]s_Delay=R"

// MSG0_RTOS_STARTING_SCHEDULER
// >>RTOS_MAIN "%N %t Starting the FreeRTOS scheduler\n"
// >RTOS_TIMING "s Kernel=Scheduler started"

// MSG1_RTOS_INCREASE_TICK_COUNT
// >>RTOS_MAIN "%N %t TaskStepTick(%u)\n"
// >RTOS_TIMING "f IncreaseTickCount=%u"

// MSG0_RTOS_LOW_POWER_IDLE_BEGIN
// >>RTOS_MAIN "%N %t Low power idle begin\n"
// >RTOS_TIMING "b Low_power_idle=1"

// MSG0_RTOS_LOW_POWER_IDLE_END
// >>RTOS_MAIN "%N %t Low power idle end\n"
// >RTOS_TIMING "b Low_power_idle=0"

// MSG1_RTOS_TASK_SWITCHED_OUT
// >>RTOS_MAIN "%N %t Task%[32u]<M_LAST_TASK_NAME>s switched out\n"

// MSG2_RTOS_TASK_PRIORITY_INHERIT
// >>RTOS_MAIN "%N %t QueueSemaphoreTake - task attempted to take a mutex that was "
// >>RTOS_MAIN "already held by a lower priority Task%[32s]s with priority %u\n"
// >RTOS_TIMING "f Task%[32s]s_priority=%u"
// >RTOS_TIMING "s Task%[0:32s]s_PriorityInherit=1"

// MSG2_RTOS_TASK_PRIORITY_DISINHERIT
// >>RTOS_MAIN "%N %t QueueSend - task releases a mutex, the holding of which had resulted in the Task%[32s]s"
// >>RTOS_MAIN " inheriting the priority of a higher priority task (original task priority: %u)\n"
// >RTOS_TIMING "f Task%[32s]s_priority=%u"
// >RTOS_TIMING "s PriorityInheritTask%[0:32s]s=0"

// MSG1_RTOS_BLOCKING_ON_QUEUE_RECEIVE
// >>RTOS_MAIN "%N %t QueueReceive - Task is about to block because it cannot read from a Queue%[32s]s\n"
// >RTOS_TIMING "s Queues=Task is about to block because it cannot read from the Queue%[32s]s"

// MSG1_RTOS_BLOCKING_ON_QUEUE_PEEK
// >>RTOS_MAIN "%N %t QueuePeek - Task is about to block because it cannot read from a Queue%[32s]s\n"
// >RTOS_TIMING "s Queues=Task is about to block because it cannot read from the Queue%[32s]s"

// MSG2_RTOS_BLOCKING_ON_QUEUE_SEND
// >>RTOS_MAIN "%N %t QueueSend - Task is about to block because it cannot write to a Queue%[32s]s:"
// >>RTOS_MAIN " copy position = %{queueSEND_TO_BACK|queueSEND_TO_FRONT|queueOVERWRITE}Y\n"
// >RTOS_TIMING "s Queues=Task is about to block because it cannot write to the Queue%[32s]s"

// MSG1_RTOS_MOVED_TASK_TO_READY_STATE
// >>RTOS_MAIN "%N %t Task%[32s]s moved to ready list\n"

// MSG1_RTOS_POST_MOVED_TASK_TO_READY_STATE
// >>RTOS_MAIN "%N %t Post Task%[32s]s moved to ready state\n"

// MSG1_RTOS_MOVED_TASK_TO_DELAYED_LIST
// >>RTOS_MAIN "%N %t Task%[32s]s moved to delayed list\n"

// MSG1_RTOS_MOVED_TASK_TO_OVERFLOW_DELAYED_LIST
// >>RTOS_MAIN "%N %t Task%[32s]s moved to overflow delayed list\n"

// MSG2_RTOS_QUEUE_REGISTRY_ADD
// >>RTOS_MAIN "%N %t Queue registry add: xQueue address 0x%08X, name %[32s]s\n"

// MSG2_RTOS_QUEUE_CREATE
// >>RTOS_MAIN "%N %t Queue%[32s]s created - "
// >>RTOS_MAIN "%{queueQUEUE_TYPE_BASE|queueQUEUE_TYPE_MUTEX|queueQUEUE_TYPE_COUNTING_SEMAPHORE|queueQUEUE_TYPE_BINARY_SEMAPHORE|queueQUEUE_TYPE_RECURSIVE_MUTEX|queueQUEUE_TYPE_SET}Y\n"
// >RTOS_TIMING "s Queues=Queue%[32s]s created"

// MSG1_RTOS_QUEUE_CREATE_FAILED
// >>RTOS_MAIN "%N %t Queue create failed - "
// >>RTOS_MAIN "%{queueQUEUE_TYPE_BASE|queueQUEUE_TYPE_MUTEX|queueQUEUE_TYPE_COUNTING_SEMAPHORE|queueQUEUE_TYPE_BINARY_SEMAPHORE|queueQUEUE_TYPE_RECURSIVE_MUTEX|queueQUEUE_TYPE_SET}Y\n"
// >RTOS_ERRORS "%N %t Queue create failed - "
// >RTOS_ERRORS "%{queueQUEUE_TYPE_BASE|queueQUEUE_TYPE_MUTEX|queueQUEUE_TYPE_COUNTING_SEMAPHORE|queueQUEUE_TYPE_BINARY_SEMAPHORE|queueQUEUE_TYPE_RECURSIVE_MUTEX|queueQUEUE_TYPE_SET}Y\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Queue create failed"
// >RTOS_TIMING "s Queues=Queue create failed"

// MSG1_RTOS_CREATE_MUTEX
// >>RTOS_MAIN "%N %t Mutex_%[32s]s created as Queue%[0:32]s\n"
// >RTOS_TIMING "s Mutex=Created as Queue%[32s]s"

// MSG0_RTOS_CREATE_MUTEX_FAILED
// >>RTOS_MAIN "%N %t Create mutex failed\n"
// >RTOS_ERRORS "%N %t Create mutex failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Create mutex failed"
// >RTOS_TIMING "s Mutex=Create failed"

// MSG1_RTOS_GIVE_MUTEX_RECURSIVE
// >>RTOS_MAIN "%N %t Give mutex recursive(Queue%[32s]s) successful\n"
// >RTOS_TIMING "s Mutex=Give recursive Queue%[32s]s success"

// MSG1_RTOS_GIVE_MUTEX_RECURSIVE_FAILED
// >>RTOS_MAIN "%N %t Give mutex recursive(Queue%[32s]s) failed\n"
// >RTOS_ERRORS "%N %t Give mutex recursive(Queue%[32s]s) failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Give mutex Queue%[32s]s recursive failed"
// >RTOS_TIMING "s Mutex=Give mutex Queue%[0:32s]s recursive failed"

// MSG1_RTOS_TAKE_MUTEX_RECURSIVE
// >>RTOS_MAIN "%N %t Take mutex recursive(Queue%[32s]s) successful\n"
// >RTOS_TIMING "s Mutex=Give mutex Queue%[0:32s]s recursive success"

// MSG1_RTOS_TAKE_MUTEX_RECURSIVE_FAILED
// >>RTOS_MAIN "%N %t Take mutex recursive(Queue%[32s]s) failed\n"
// >RTOS_ERRORS "%N %t Take mutex recursive(Queue%[32s]s) failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Take mutex Queue%[32s]s recursive failed"
// >RTOS_TIMING "s Mutex=Take mutex Queue%[0:32s]s recursive failed"

// MSG3_RTOS_CREATE_COUNTING_SEMAPHORE
// >>RTOS_MAIN "%N %t Create counting semaphore Queue%[32s]s successful, max. count %u, initial count %u\n"
// >RTOS_TIMING "s Queues=Counting semaphore Queue%[32s]s created"
// >RTOS_TIMING "s Semaphore=Counting semaphore Queue%[32s]s created"

// MSG0_RTOS_CREATE_COUNTING_SEMAPHORE_FAILED
// >>RTOS_MAIN "%N %t Create counting semaphore failed\n"
// >RTOS_ERRORS "%N %t Create counting semaphore failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Create counting semaphore failed"
// >RTOS_TIMING "s Semaphore=Create counting semaphore failed"

// MSG2_RTOS_QUEUE_SEND
// >>RTOS_MAIN "%N %t QueueSend to Queue%[32s]s successful, %[32:32u](+1)u items in queue\n"
// >RTOS_TIMING "f Queue%[32s]s_items=%[32:32u](+1)u"

// MSG2_RTOS_QUEUE_SEND_FAILED
// >>RTOS_MAIN "%N %t QueueSend to Queue%[32s]s failed: TicksToWait %[28]u, "
// >>RTOS_MAIN "CopyPosition %[4]{queueSEND_TO_BACK|queueSEND_TO_FRONT|queueOVERWRITE}Y\n"
// >RTOS_ERRORS "%N %t QueueSend to Queue%[32s]s failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Queue%[32s]s send failed"
// >RTOS_TIMING "s Queues=Queue%[0:32s]s send failed"

// MSG2_RTOS_QUEUE_RECEIVE
// >>RTOS_MAIN "%N %t QueueReceive from Queue%[32s]s successful, ticks to wait %[16u]u, %[16u]u items in queue\n"
// >RTOS_TIMING "f Queue%[32s]s_items=%[48:16u](-1)u"

// MSG2_RTOS_QUEUE_PEEK
// >>RTOS_MAIN "%N %t QueuePeek from Queue%[32s]s successful, ticks to wait %u\n"
// >RTOS_TIMING "b Queue%[32s]s_peek=P"

// MSG2_RTOS_QUEUE_PEEK_FAILED
// >>RTOS_MAIN "%N %t QueuePeek from Queue%[32s]s failed, ticks to wait %u\n"
// >RTOS_ERRORS "%N %t QueuePeek from Queue%[32s]s failed, ticks to wait %u\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Queue%[32s]s peek failed"
// >RTOS_TIMING "s Queues=Queue%[0:32s]s peek failed"

// MSG1_RTOS_QUEUE_PEEK_FROM_ISR
// >>RTOS_MAIN "%N %t Queue%[32s]s peek from ISR successful\n"
// >RTOS_TIMING "b Queue%[32s]s_peek_ISR=P"

// MSG2_RTOS_QUEUE_RECEIVE_FAILED
// >>RTOS_MAIN "%N %t QueueReceive from Queue%[32s]s failed, ticks to wait %u\n"
// >RTOS_ERRORS "%N %t QueueReceive from Queue%[32s]s failed, ticks to wait %u\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Queue%[32s]s receive failed"
// >RTOS_TIMING "s Queues=Queue%[0:32s]s receive failed"

// MSG2_RTOS_QUEUE_SEND_FROM_ISR
// >>RTOS_MAIN "%N %t QueueSendFromISR to Queue%[32s]s successful, %u items in queue\n"
// >RTOS_TIMING "f Queue%[32s]s_items=%[32:32u](+1)u"

// MSG1_RTOS_QUEUE_SEND_FROM_ISR_FAILED
// >>RTOS_MAIN "%N %t QueueSendFromISR to Queue%[32s]s failed\n"
// >RTOS_ERRORS "%N %t QueueSendFromISR to Queue%[32s]s failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Queue%[32s]s send from ISR failed"
// >RTOS_TIMING "s Queues=Queue%[0:32s]s send from ISR failed"

// MSG2_RTOS_QUEUE_RECEIVE_FROM_ISR
// >>RTOS_MAIN "%N %t QueueReceiveFromISR from Queue%[32s]s successful, %u items in queue\n"
// >RTOS_TIMING "f Queue%[32s]s_items=%[32:32u](-1)u"

// MSG1_RTOS_QUEUE_RECEIVE_FROM_ISR_FAILED
// >>RTOS_MAIN "%N %t QueueReceiveFromISR from Queue%[32s]s failed\n"
// >RTOS_ERRORS "%N %t QueueReceiveFromISR from Queue%[32s]s failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Queue%[32s]s receive from ISR failed"
// >RTOS_TIMING "s Queues=Queue%[0:32s]s receive from ISR failed"

// MSG1_RTOS_QUEUE_DELETE
// >>RTOS_MAIN "%N %t Queue%[32s]s deleted\n"
// >RTOS_TIMING "s Queues=Queue%[32s]s deleted"

// MSG1_RTOS_QUEUE_PEEK_FROM_ISR_FAILED
// >>RTOS_MAIN "%N %t QueuePeekFromISR from Queue%[32s]s failed\n"
// >RTOS_ERRORS "%N %t QueuePeekFromISR from Queue%[32s]s failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Queue%[32s]s peek from ISR failed"
// >RTOS_TIMING "s Queues=Queue%[0:32s]s peek from ISR failed"

// MSG1_RTOS_TASK_CREATE
// >>RTOS_MAIN "%N %t xTaskCreate Task%[32s]s successful\n"
// >RTOS_TIMING "s Kernel=Task%[32s]s created"

// MSG0_RTOS_TASK_CREATE_FAILED
// >>RTOS_MAIN "%N %t TaskCreate failed\n"
// >RTOS_ERRORS "%N %t TaskCreate failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Task create failed"
// >RTOS_TIMING "s Kernel=Task create failed"

// MSG1_RTOS_TASK_DELETE
// >>RTOS_MAIN "%N %t TaskDelete Task%[32s]s successful\n"
// >RTOS_TIMING "s Kernel=Task%[32s]s deleted"

// MSG1_RTOS_TASK_DELAY_UNTIL
// >>RTOS_MAIN "%N %t TaskDelayUntil %u\n"
// >RTOS_TIMING "s Task%[M_LAST_TASK_NAME]s_DelayUntil=%u"

// MSG1_RTOS_TASK_DELAY
// >>RTOS_MAIN "%N %t TaskDelay for %u ticks\n"
// >RTOS_TIMING "f Task%[M_LAST_TASK_NAME]s_Delay=%u"

// MSG2_RTOS_TASK_PRIORITY_SET
// >>RTOS_MAIN "%N %t TaskPrioritySet for Task%[32s]s to %u\n"
// >RTOS_TIMING "f Task%[32s]s_priority=%u"

// MSG1_RTOS_TASK_SUSPEND
// >>RTOS_MAIN "%N %t TaskSuspend Task%[32s]s\n"
// >RTOS_TIMING "b Task%[32s]s_Suspended=1"

// MSG1_RTOS_TASK_RESUME
// >>RTOS_MAIN "%N %t TaskResume Task%[32s]s\n"
// >RTOS_TIMING "b Task%[32s]s_Suspended=0"

// MSG1_RTOS_TASK_RESUME_FROM_ISR
// >>RTOS_MAIN "%N %t TaskResumeFromISR Task%[32s]s\n"
// >RTOS_TIMING "b Task%[32s]s_Suspended=0"

// MSG1_RTOS_TASK_INCREMENT_TICK
// >>RTOS_MAIN "%N %t Task increment tick - xTickCount: %u\n"
// >RTOS_TIMING "f IncrementTick=%u"

// MSG2_RTOS_TIMER_CREATE
// >>RTOS_MAIN "%N %t TimerCreate - Timer%[32s]s: period %u ticks\n"
// >RTOS_TIMING "s Timer%[32s]s=Created"

// MSG0_RTOS_TIMER_CREATE_FAILED
// >>RTOS_MAIN "%N %t Timer create failed\n"
// >RTOS_ERRORS "%N %t Timer create failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Timer create failed"

// EXT_MSG3_1_RTOS_TIMER_COMMAND_SEND
// >>RTOS_MAIN "%N %t Timer%[32s]s command sent: message ID %u, value %u, returns %{pdFAIL|pdPASS}Y\n"
// >RTOS_TIMING "s Timer%[32s]s=Command sent: ID %u, value %u, returns %{pdFAIL|pdPASS}Y"

// MSG1_RTOS_TIMER_EXPIRED
// >>RTOS_MAIN "%N %t Timer%[32s]s expired\n"
// >RTOS_TIMING "s Timer%[32s]s=Expired"

// MSG3_RTOS_TIMER_COMMAND_RECEIVED
// >>RTOS_MAIN "%N %t Timer%[32s]s command received: message ID %u, value %u\n"
// >RTOS_TIMING "s Timer%[32s]s=Command received: ID %u, value %u"

// MSG2_RTOS_MALLOC
// >>RTOS_MAIN "%N %t Malloc: address 0x%08X, size %u bytes\n"
// >RTOS_TIMING "f Malloc_Free=%[32:32u]u"

// MSG2_RTOS_FREE
// >>RTOS_MAIN "%N %t Free: address 0x%08X, size %u bytes\n"
// >RTOS_TIMING "f Malloc_Free=%[32:32u](*-1.)d"

// MSG1_RTOS_EVENT_GROUP_CREATE
// >>RTOS_MAIN "%N %t Event group created: address 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Created"

// MSG0_RTOS_EVENT_GROUP_CREATE_FAILED
// >>RTOS_MAIN "%N %t Event group create failed\n"
// >RTOS_ERRORS "%N %t Event group create failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Event group create failed"

// MSG3_RTOS_EVENT_GROUP_SYNC_BLOCK
// >>RTOS_MAIN "%N %t Event group sync block: address 0x%08X, BitsToSet 0x%08X, BitsToWaitFor 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Sync block"

// MSG4_RTOS_EVENT_GROUP_SYNC_END
// >>RTOS_MAIN "%N %t Event group sync end: address 0x%08X, BitsToSet 0x%08X, "
// >>RTOS_MAIN "BitsToWaitFor 0x%08X, TimeoutOccurred 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Sync end"

// MSG2_RTOS_EVENT_GROUP_WAIT_BITS_BLOCK
// >>RTOS_MAIN "%N %t Event group wait bits block: address 0x%08X, BitsToWaitFor 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Wait bits block"

// MSG3_RTOS_EVENT_GROUP_WAIT_BITS_END
// >>RTOS_MAIN "%N %t Event group wait bits end: address 0x%08X, BitsToWaitFor 0x%08X, "
// >>RTOS_MAIN "TimeoutOccurred = %{FALSE|TRUE}Y\n"
// >RTOS_TIMING "s EventGroup_%08X=Wait bits end"

// MSG2_RTOS_EVENT_GROUP_CLEAR_BITS
// >>RTOS_MAIN "%N %t Event group clear bits: address 0x%08X, BitsToClear 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Clear bits"

// MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_FROM_ISR
// >>RTOS_MAIN "%N %t Event group clear bits from ISR: address 0x%08X, BitsToClear 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Clear bits from ISR"

// MSG2_RTOS_EVENT_GROUP_SET_BITS
// >>RTOS_MAIN "%N %t Event group set bits: address 0x%08X, BitsToSet 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Set bits"

// MSG2_RTOS_EVENT_GROUP_SET_BITS_FROM_ISR
// >>RTOS_MAIN "%N %t Event group set bits from ISR: address 0x%08X, BitsToSet 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Set bits from ISR"

// MSG1_RTOS_EVENT_GROUP_DELETE
// >>RTOS_MAIN "%N %t Event group delete: address 0x%08X\n"
// >RTOS_TIMING "s EventGroup_%08X=Delete"

// MSG4_RTOS_PEND_FUNC_CALL
// >>RTOS_MAIN "%N %t Timer function call: FunctionToPend: address 0x%08X, Parameter1 %u, "
// >>RTOS_MAIN "Parameter2 %u, Return %u\n"
// >RTOS_TIMING "b PendFuncCall=P"

// MSG4_RTOS_PEND_FUNC_CALL_FROM_ISR
// >>RTOS_MAIN "%N %t Timer function call from ISR: FunctionToPend: address 0x%08X, "
// >>RTOS_MAIN "Parameter1 %u, Parameter2 %u, Return %u\n"
// >RTOS_TIMING "b PendFuncCall_ISR=P"

/*---- Trace task notification macros for FreeRTOS versions 10.4.0 (2) and later (1) ----*/
// MSG3_RTOS_TASK_NOTIFY_TAKE_BLOCK1
// >>RTOS_MAIN "%N %t TaskNotifyTake block: Task%[32s]s, IndexToWait %[16]u"
// >>RTOS_MAIN ", ClearCountOnExit = %[16]{FALSE|TRUE}Y, TicksToWait %u\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyTake=P"

// MSG2_RTOS_TASK_NOTIFY_TAKE_BLOCK2
// >>RTOS_MAIN "%N %t TaskNotifyTake block: Task%[32s]s"
// >>RTOS_MAIN ", ClearCountOnExit = %[1]{FALSE|TRUE}Y, TicksToWait %[31]u\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyTake=P"

// MSG3_RTOS_TASK_NOTIFY_TAKE1
// >>RTOS_MAIN "%N %t TaskNotifyTake: Task%[32s]s, IndexToWait %[16]u"
// >>RTOS_MAIN ", ClearCountOnExit = %[16]{FALSE|TRUE}Y, TicksToWait %u\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyTake=P"

// MSG2_RTOS_TASK_NOTIFY_TAKE2
// >>RTOS_MAIN "%N %t TaskNotifyTake: Task%[32s]s"
// >>RTOS_MAIN ", ClearCountOnExit = %[1]{FALSE|TRUE}Y, TicksToWait %[31]u\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyTake=P"

// MSG4_RTOS_TASK_NOTIFY_WAIT_BLOCK1
// >>RTOS_MAIN "%N %t TaskNotifyWait block: Task%[32s]s, IndexToWait %[8]u, TicksToWait %[24]u"
// >>RTOS_MAIN ", BitsToClearOnEntry 0x%08X, BitsToClearOnExit 0x%08X\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyWait=P"

// MSG4_RTOS_TASK_NOTIFY_WAIT_BLOCK2
// >>RTOS_MAIN "%N %t TaskNotifyWait block: Task%[32s]s, TicksToWait %u"
// >>RTOS_MAIN ", BitsToClearOnEntry 0x%08X, BitsToClearOnExit 0x%08X\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyWait=P"

// MSG4_RTOS_TASK_NOTIFY_WAIT1
// >>RTOS_MAIN "%N %t TaskNotifyWait: Task%[32s]s, IndexToWait %[8]u, TicksToWait %[24]u"
// >>RTOS_MAIN ", BitsToClearOnEntry 0x%08X, BitsToClearOnExit 0x%08X\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyWait=P"

// MSG4_RTOS_TASK_NOTIFY_WAIT2
// >>RTOS_MAIN "%N %t TaskNotifyWait: Task%[32s]s, TicksToWait %u"
// >>RTOS_MAIN ", BitsToClearOnEntry 0x%08X, BitsToClearOnExit 0x%08X\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyWait=P"

// MSG3_RTOS_TASK_NOTIFY1
// >>RTOS_MAIN "%N %t TaskNotify Task%[32s]s: IndexToNotify %[16]u, "
// >>RTOS_MAIN "Action %[16]{eNoAction|eSetBits|eIncrement|eSetValueWithOverwrite|eSetValueWithoutOverwrite}Y"
// >>RTOS_MAIN ", Value %u\n"
// >RTOS_TIMING "b Task%[32s]s_Notify=P"

// MSG3_RTOS_TASK_NOTIFY2
// >>RTOS_MAIN "%N %t TaskNotify Task%[32s]s: "
// >>RTOS_MAIN "Action = %{eNoAction|eSetBits|eIncrement|eSetValueWithOverwrite|eSetValueWithoutOverwrite}Y"
// >>RTOS_MAIN ", Value %u\n"
// >RTOS_TIMING "b Task%[32s]s_Notify=P"

// MSG3_RTOS_TASK_NOTIFY_FROM_ISR1
// >>RTOS_MAIN "%N %t TaskNotifyFromISR Task%[32s]s: IndexToNotify %[16]u, "
// >>RTOS_MAIN "Action %[16]{eNoAction|eSetBits|eIncrement|eSetValueWithOverwrite|eSetValueWithoutOverwrite}Y"
// >>RTOS_MAIN ", Value %u\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyISR=P"

// MSG3_RTOS_TASK_NOTIFY_FROM_ISR2
// >>RTOS_MAIN "%N %t TaskNotifyFromISR Task%[32s]s: "
// >>RTOS_MAIN "Action %{eNoAction|eSetBits|eIncrement|eSetValueWithOverwrite|eSetValueWithoutOverwrite}Y"
// >>RTOS_MAIN ", Value %u\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyISR=P"

// MSG2_RTOS_TASK_NOTIFY_GIVE_FROM_ISR1
// >>RTOS_MAIN "%N %t TaskNotifyGiveFromISR Task%[32s]s: IndexToNotify %[16]u\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyGiveISR=P"

// MSG1_RTOS_TASK_NOTIFY_GIVE_FROM_ISR2
// >>RTOS_MAIN "%N %t TaskNotifyGiveFromISR Task%[32s]s\n"
// >RTOS_TIMING "b Task%[32s]s_NotifyGiveISR=P"
/*------------------------------------------------------------------------------------------------*/

// MSG0_RTOS_ISR_EXIT_TO_SCHEDULER
// >>RTOS_MAIN "%N %t ISR exit to scheduler\n"

// MSG0_RTOS_ISR_EXIT
// >>RTOS_MAIN "%N %t ISR exit\n"

// MSG0_RTOS_ISR_ENTER
// >>RTOS_MAIN "%N %t RTOS Tick ISR enter\n"
// >RTOS_TIMING "b RTOStickIRQ=P"

/*---- Trace FreeRTOS stream and message buffer operations. ----*/
// MSG1_RTOS_STREAM_BUFFER_CREATE_FAILED
// >>RTOS_MAIN "%N %t Stream buffer create failed: "
// >>RTOS_MAIN "type = %{TYPE_STREAM_BUFFER|TYPE_MESSAGE_BUFFER|TYPE_STREAM_BATCHING_BUFFER}Y\n"
// >RTOS_ERRORS "%N %t Stream buffer create failed: "
// >RTOS_ERRORS "type = %{TYPE_STREAM_BUFFER|TYPE_MESSAGE_BUFFER|TYPE_STREAM_BATCHING_BUFFER}Y\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Stream buffer create failed"

// MSG1_RTOS_STREAM_BUFFER_CREATE_STATIC_FAILED
// >>RTOS_MAIN "%N %t Stream buffer create static failed: "
// >>RTOS_MAIN "type = %{TYPE_STREAM_BUFFER|TYPE_MESSAGE_BUFFER|TYPE_STREAM_BATCHING_BUFFER}Y\n"
// >RTOS_ERRORS "%N %t Stream buffer create static failed: "
// >RTOS_ERRORS "type = %{TYPE_STREAM_BUFFER|TYPE_MESSAGE_BUFFER|TYPE_STREAM_BATCHING_BUFFER}Y\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Stream buffer create static failed"

// MSG2_RTOS_STREAM_BUFFER_CREATE
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X create successful: "
// >>RTOS_MAIN "type = %{TYPE_STREAM_BUFFER|TYPE_MESSAGE_BUFFER|TYPE_STREAM_BATCHING_BUFFER}Y\n"
// >RTOS_TIMING "s Stream_%08X=Created"

// MSG1_RTOS_STREAM_BUFFER_DELETE
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X delete\n"
// >RTOS_TIMING "s Stream_%08X=Deleted"

// MSG1_RTOS_STREAM_BUFFER_RESET
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X reset\n"
// >RTOS_TIMING "s Stream_%08X=Reset"

// MSG1_RTOS_STREAM_BUFFER_RESET_FROM_ISR
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X reset from ISR\n"
// >RTOS_TIMING "s Stream_%08X=Reset from ISR"

// MSG1_RTOS_BLOCKING_ON_STREAM_BUFFER_SEND
// >>RTOS_MAIN "%N %t Blocking on stream buffer 0x%08X send\n"
// >RTOS_TIMING "s Stream_%08X=Blocking on send"

// MSG2_RTOS_STREAM_BUFFER_SEND
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X send, BytesSent %u\n"
// >RTOS_TIMING "f Stream_%08X_bytes=%u"

// MSG1_RTOS_STREAM_BUFFER_SEND_FAILED
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X send failed\n"
// >RTOS_ERRORS "%N %t Stream buffer 0x%08X send failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Stream buffer %08X send failed"
// >RTOS_TIMING "s Stream_%[0:32u]08X=Send failed"

// MSG2_RTOS_STREAM_BUFFER_SEND_FROM_ISR
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X send from ISR, BytesSent %u\n"
// >RTOS_TIMING "f Stream_%08X_bytes=%u"

// MSG1_RTOS_BLOCKING_ON_STREAM_BUFFER_RECEIVE
// >>RTOS_MAIN "%N %t Blocking on stream buffer 0x%08X receive\n"
// >RTOS_TIMING "s Stream_%08X=Blocking on receive"

// MSG2_RTOS_STREAM_BUFFER_RECEIVE
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X receive, ReceivedLength %u\n"
// >RTOS_TIMING "f Stream_%08X_bytes=-%u"

// MSG1_RTOS_STREAM_BUFFER_RECEIVE_FAILED
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X receive failed\n"
// >RTOS_ERRORS "%N %t Stream buffer 0x%08X receive failed\n"
// >RTOS_TIMING "b RTOSerror=P"
// >RTOS_TIMING "s RTOSerrorText=Stream buffer %08X receive failed"
// >RTOS_TIMING "s Stream_%[0:32u]08X=Receive failed"

// MSG2_RTOS_STREAM_BUFFER_RECEIVE_FROM_ISR
// >>RTOS_MAIN "%N %t Stream buffer 0x%08X receive from ISR, ReceivedLength %u\n"
// >RTOS_TIMING "f Stream_%08X_bytes=-%u"

#endif
