#ifndef RTE_RTE_FREERTOS_TRACE2_FMT_H
#define RTE_RTE_FREERTOS_TRACE2_FMT_H

/*-------------------------------------------------------------------------*/
/* @file    rte_FreeRTOS_trace2_fmt.h                                      */
/* @author  Branko Premzel                                                 */
/* @brief   RTEdbg format definitions for the FreeRTOS ENTER/RETURN trace. */
/*          Definitions for the macros that are in rte_FreeRTOS_trace2.h.  */
/* SPDX-License-Identifier: MIT                                            */
/*-------------------------------------------------------------------------*/


/*-------------- Define the message filter names ---------------*/
// FILTER(F_RTOS_TRACE_IO, "FreeRTOS ENTER/RETURN")
#define F_RTOS_TRACE_IO 8U

/*--------------------------------------------------------------------------------*/
/*---- Printf strings for the trace macros defined in "rte_FreeRTOS_trace2.h" ----*/
/*--------------------------------------------------------------------------------*/

// MSG1_RTOS_EVENT_GROUP_CREATE_STATIC_ENTER ""
#define MSG1_RTOS_EVENT_GROUP_CREATE_STATIC_ENTER 422U
// >>RTOS_MAIN "%N %t xEventGroupCreateStatic ENTER: pxEventGroupBuffer 0x%08X\n"

// MSG1_RTOS_EVENT_GROUP_CREATE_STATIC_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_CREATE_STATIC_RETURN 428U
// >>RTOS_MAIN "%N %t xEventGroupCreateStatic RETURN: pxEventBits 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_EVENT_GROUP_CREATE_STATIC_ENTER](*1e6).3f us\n"

// MSG0_RTOS_EVENT_GROUP_CREATE_ENTER ""
#define MSG0_RTOS_EVENT_GROUP_CREATE_ENTER 387U
// >>RTOS_MAIN "%N %t xEventGroupCreate ENTER\n"

// MSG1_RTOS_EVENT_GROUP_CREATE_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_CREATE_RETURN 430U
// >>RTOS_MAIN "%N %t xEventGroupCreate RETURN: pxEventBits 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_EVENT_GROUP_CREATE_ENTER](*1e6).3f us\n"

// MSG4_RTOS_EVENT_GROUP_SYNC_ENTER ""
#define MSG4_RTOS_EVENT_GROUP_SYNC_ENTER 432U
// >>RTOS_MAIN "%N %t xEventGroupSync ENTER: xEventGroup 0x%08X, uxBitsToSet 0x%08X, "
// >>RTOS_MAIN "uxBitsToWaitFor 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_EVENT_GROUP_SYNC_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_SYNC_RETURN 448U
// >>RTOS_MAIN "%N %t xEventGroupSync RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_EVENT_GROUP_SYNC_ENTER](*1e6).3f us\n"

// MSG5_RTOS_EVENT_GROUP_WAIT_BITS_ENTER ""
#define MSG5_RTOS_EVENT_GROUP_WAIT_BITS_ENTER 464U
// >>RTOS_MAIN "%N %t xEventGroupWaitBits ENTER: xEventGroup 0x%08X, uxBitsToWaitFor 0x%08X, "
// >>RTOS_MAIN "xClearOnExit %u, xWaitForAllBits %u, xTicksToWait %u\n"

// MSG1_RTOS_EVENT_GROUP_WAIT_BITS_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_WAIT_BITS_RETURN 450U
// >>RTOS_MAIN "%N %t xEventGroupWaitBits RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG5_RTOS_EVENT_GROUP_WAIT_BITS_ENTER](*1e6).3f us\n"

// MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_ENTER ""
#define MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_ENTER 452U
// >>RTOS_MAIN "%N %t xEventGroupClearBits ENTER: xEventGroup 0x%08X, uxBitsToClear 0x%08X\n"

// MSG1_RTOS_EVENT_GROUP_CLEAR_BITS_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_CLEAR_BITS_RETURN 456U
// >>RTOS_MAIN "%N %t xEventGroupClearBits RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_ENTER](*1e6).3f us\n"

// MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_FROM_ISR_ENTER ""
#define MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_FROM_ISR_ENTER 460U
// >>RTOS_MAIN "%N %t xEventGroupClearBitsFromISR ENTER: xEventGroup 0x%08X, uxBitsToClear 0x%08X\n"

// MSG1_RTOS_EVENT_GROUP_CLEAR_BITS_FROM_ISR_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_CLEAR_BITS_FROM_ISR_RETURN 458U
// >>RTOS_MAIN "%N %t xEventGroupClearBitsFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_EVENT_GROUP_GET_BITS_FROM_ISR_ENTER ""
#define MSG1_RTOS_EVENT_GROUP_GET_BITS_FROM_ISR_ENTER 480U
// >>RTOS_MAIN "%N %t xEventGroupGetBitsFromISR ENTER: xEventGroup 0x%08X\n"

// MSG1_RTOS_EVENT_GROUP_GET_BITS_FROM_ISR_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_GET_BITS_FROM_ISR_RETURN 482U
// >>RTOS_MAIN "%N %t xEventGroupGetBitsFromISR RETURN: uxReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_EVENT_GROUP_GET_BITS_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_EVENT_GROUP_SET_BITS_ENTER ""
#define MSG2_RTOS_EVENT_GROUP_SET_BITS_ENTER 484U
// >>RTOS_MAIN "%N %t xEventGroupSetBits ENTER: xEventGroup 0x%08X, uxBitsToSet 0x%08X\n"

// MSG1_RTOS_EVENT_GROUP_SET_BITS_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_SET_BITS_RETURN 488U
// >>RTOS_MAIN "%N %t xEventGroupSetBits RETURN: uxEventBits 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_EVENT_GROUP_SET_BITS_ENTER](*1e6).3f us\n"

// MSG1_RTOS_EVENT_GROUP_DELETE_ENTER ""
#define MSG1_RTOS_EVENT_GROUP_DELETE_ENTER 490U
// >>RTOS_MAIN "%N %t vEventGroupDelete ENTER: xEventGroup 0x%08X\n"

// MSG0_RTOS_EVENT_GROUP_DELETE_RETURN ""
#define MSG0_RTOS_EVENT_GROUP_DELETE_RETURN 492U
// >>RTOS_MAIN "%N %t vEventGroupDelete RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_EVENT_GROUP_DELETE_ENTER](*1e6).3f us\n"

// MSG2_RTOS_EVENT_GROUP_GET_STATIC_BUFFER_ENTER ""
#define MSG2_RTOS_EVENT_GROUP_GET_STATIC_BUFFER_ENTER 496U
// >>RTOS_MAIN "%N %t xEventGroupGetStaticBuffer ENTER: xEventGroup 0x%08X, ppxEventGroupBuffer 0x%08X\n"

// MSG1_RTOS_EVENT_GROUP_GET_STATIC_BUFFER_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_GET_STATIC_BUFFER_RETURN 494U
// >>RTOS_MAIN "%N %t xEventGroupGetStaticBuffer RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_EVENT_GROUP_GET_STATIC_BUFFER_ENTER](*1e6).3f us\n"

// MSG2_RTOS_EVENT_GROUP_SET_BITS_CALLBACK_ENTER ""
#define MSG2_RTOS_EVENT_GROUP_SET_BITS_CALLBACK_ENTER 500U
// >>RTOS_MAIN "%N %t vEventGroupSetBitsCallback ENTER: pvEventGroup 0x%08X, ulBitsToSet 0x%08X\n"

// MSG0_RTOS_EVENT_GROUP_SET_BITS_CALLBACK_RETURN ""
#define MSG0_RTOS_EVENT_GROUP_SET_BITS_CALLBACK_RETURN 493U
// >>RTOS_MAIN "%N %t vEventGroupSetBitsCallback RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_EVENT_GROUP_SET_BITS_CALLBACK_ENTER](*1e6).3f us\n"

// MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_CALLBACK_ENTER ""
#define MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_CALLBACK_ENTER 504U
// >>RTOS_MAIN "%N %t vEventGroupClearBitsCallback ENTER: pvEventGroup 0x%08X, ulBitsToClear 0x%08X\n"

// MSG0_RTOS_EVENT_GROUP_CLEAR_BITS_CALLBACK_RETURN ""
#define MSG0_RTOS_EVENT_GROUP_CLEAR_BITS_CALLBACK_RETURN 508U
// >>RTOS_MAIN "%N %t vEventGroupClearBitsCallback RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_EVENT_GROUP_CLEAR_BITS_CALLBACK_ENTER](*1e6).3f us\n"

// MSG3_RTOS_EVENT_GROUP_SET_BITS_FROM_ISR_ENTER ""
#define MSG3_RTOS_EVENT_GROUP_SET_BITS_FROM_ISR_ENTER 512U
// >>RTOS_MAIN "%N %t xEventGroupSetBitsFromISR ENTER: xEventGroup 0x%08X, uxBitsToSet 0x%08X, "
// >>RTOS_MAIN "pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_EVENT_GROUP_SET_BITS_FROM_ISR_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_SET_BITS_FROM_ISR_RETURN 510U
// >>RTOS_MAIN "%N %t xEventGroupSetBitsFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_EVENT_GROUP_SET_BITS_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_EVENT_GROUP_GET_NUMBER_ENTER ""
#define MSG1_RTOS_EVENT_GROUP_GET_NUMBER_ENTER 520U
// >>RTOS_MAIN "%N %t uxEventGroupGetNumber ENTER: xEventGroup 0x%08X\n"

// MSG1_RTOS_EVENT_GROUP_GET_NUMBER_RETURN ""
#define MSG1_RTOS_EVENT_GROUP_GET_NUMBER_RETURN 522U
// >>RTOS_MAIN "%N %t uxEventGroupGetNumber RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_EVENT_GROUP_GET_NUMBER_ENTER](*1e6).3f us\n"

// MSG2_RTOS_EVENT_GROUP_SET_NUMBER_ENTER ""
#define MSG2_RTOS_EVENT_GROUP_SET_NUMBER_ENTER 524U
// >>RTOS_MAIN "%N %t vEventGroupSetNumber ENTER: xEventGroup 0x%08X, uxEventGroupNumber %u\n"

// MSG0_RTOS_EVENT_GROUP_SET_NUMBER_RETURN ""
#define MSG0_RTOS_EVENT_GROUP_SET_NUMBER_RETURN 509U
// >>RTOS_MAIN "%N %t vEventGroupSetNumber RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_EVENT_GROUP_SET_NUMBER_ENTER](*1e6).3f us\n"

// MSG7_RTOS_TASK_CREATE_STATIC_ENTER ""
#define MSG7_RTOS_TASK_CREATE_STATIC_ENTER 528U
// >>RTOS_MAIN "%N %t xTaskCreateStatic ENTER: pxTaskCode 0x%08X, pcName 0x%08X, uxStackDepth %u, "
// >>RTOS_MAIN "pvParameters 0x%08X, uxPriority %u, puxStackBuffer 0x%08X, "
// >>RTOS_MAIN "pxTaskBuffer 0x%08X\n"

// MSG1_RTOS_TASK_CREATE_STATIC_RETURN ""
#define MSG1_RTOS_TASK_CREATE_STATIC_RETURN 544U
// >>RTOS_MAIN "%N %t xTaskCreateStatic RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG7_RTOS_TASK_CREATE_STATIC_ENTER](*1e6).3f us\n"

// MSG8_RTOS_TASK_CREATE_STATIC_AFFINITY_SET_ENTER ""
#define MSG8_RTOS_TASK_CREATE_STATIC_AFFINITY_SET_ENTER 560U
// >>RTOS_MAIN "%N %t xTaskCreateStaticAffinitySet ENTER: pxTaskCode 0x%08X, pcName 0x%08X, "
// >>RTOS_MAIN "uxStackDepth %u, pvParameters 0x%08X, uxPriority %u, puxStackBuffer 0x%08X, "
// >>RTOS_MAIN "pxTaskBuffer 0x%08X, uxCoreAffinityMask %u\n"

// MSG1_RTOS_TASK_CREATE_STATIC_AFFINITY_SET_RETURN ""
#define MSG1_RTOS_TASK_CREATE_STATIC_AFFINITY_SET_RETURN 546U
// >>RTOS_MAIN "%N %t xTaskCreateStaticAffinitySet RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG8_RTOS_TASK_CREATE_STATIC_AFFINITY_SET_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TASK_CREATE_RESTRICTED_STATIC_ENTER ""
#define MSG2_RTOS_TASK_CREATE_RESTRICTED_STATIC_ENTER 548U
// >>RTOS_MAIN "%N %t xTaskCreateRestrictedStatic ENTER: pxTaskDefinition 0x%08X, "
// >>RTOS_MAIN "pxCreatedTask 0x%08X\n"

// MSG1_RTOS_TASK_CREATE_RESTRICTED_STATIC_RETURN ""
#define MSG1_RTOS_TASK_CREATE_RESTRICTED_STATIC_RETURN 552U
// >>RTOS_MAIN "%N %t xTaskCreateRestrictedStatic RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TASK_CREATE_RESTRICTED_STATIC_ENTER](*1e6).3f us\n"

// MSG3_RTOS_TASK_CREATE_RESTRICTED_STATIC_AFFINITY_SET_ENTER ""
#define MSG3_RTOS_TASK_CREATE_RESTRICTED_STATIC_AFFINITY_SET_ENTER 576U
// >>RTOS_MAIN "%N %t xTaskCreateRestrictedStaticAffinitySet ENTER: pxTaskDefinition 0x%08X, "
// >>RTOS_MAIN "uxCoreAffinityMask %u, pxCreatedTask 0x%08X\n"

// MSG1_RTOS_TASK_CREATE_RESTRICTED_STATIC_AFFINITY_SET_RETURN ""
#define MSG1_RTOS_TASK_CREATE_RESTRICTED_STATIC_AFFINITY_SET_RETURN 554U
// >>RTOS_MAIN "%N %t xTaskCreateRestrictedStaticAffinitySet RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_TASK_CREATE_RESTRICTED_STATIC_AFFINITY_SET_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TASK_CREATE_RESTRICTED_ENTER ""
#define MSG2_RTOS_TASK_CREATE_RESTRICTED_ENTER 556U
// >>RTOS_MAIN "%N %t xTaskCreateRestricted ENTER: pxTaskDefinition 0x%08X, pxCreatedTask 0x%08X\n"

// MSG1_RTOS_TASK_CREATE_RESTRICTED_RETURN ""
#define MSG1_RTOS_TASK_CREATE_RESTRICTED_RETURN 584U
// >>RTOS_MAIN "%N %t xTaskCreateRestricted RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TASK_CREATE_RESTRICTED_ENTER](*1e6).3f us\n"

// MSG3_RTOS_TASK_CREATE_RESTRICTED_AFFINITY_SET_ENTER ""
#define MSG3_RTOS_TASK_CREATE_RESTRICTED_AFFINITY_SET_ENTER 592U
// >>RTOS_MAIN "%N %t xTaskCreateRestrictedAffinitySet ENTER: pxTaskDefinition 0x%08X, "
// >>RTOS_MAIN "uxCoreAffinityMask %u, pxCreatedTask 0x%08X\n"

// MSG1_RTOS_TASK_CREATE_RESTRICTED_AFFINITY_SET_RETURN ""
#define MSG1_RTOS_TASK_CREATE_RESTRICTED_AFFINITY_SET_RETURN 586U
// >>RTOS_MAIN "%N %t xTaskCreateRestrictedAffinitySet RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_TASK_CREATE_RESTRICTED_AFFINITY_SET_ENTER](*1e6).3f us\n"

// MSG6_RTOS_TASK_CREATE_ENTER ""
#define MSG6_RTOS_TASK_CREATE_ENTER 608U
// >>RTOS_MAIN "%N %t xTaskCreate ENTER: pxTaskCode: 0x%08X, pcName 0x%08X, uxStackDepth %u, "
// >>RTOS_MAIN "pvParameters 0x%08X, uxPriority %u, pxCreatedTask 0x%08X\n"

// MSG1_RTOS_TASK_CREATE_RETURN ""
#define MSG1_RTOS_TASK_CREATE_RETURN 588U
// >>RTOS_MAIN "%N %t xTaskCreate RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG6_RTOS_TASK_CREATE_ENTER](*1e6).3f us\n"

// MSG7_RTOS_TASK_CREATE_AFFINITY_SET_ENTER ""
#define MSG7_RTOS_TASK_CREATE_AFFINITY_SET_ENTER 624U
// >>RTOS_MAIN "%N %t xTaskCreateAffinitySet ENTER: pxTaskCode 0x%08X, pcName 0x%08X, uxStackDepth %u, "
// >>RTOS_MAIN "pvParameters 0x%08X, uxPriority %u, uxCoreAffinityMask %u, pxCreatedTask 0x%08X\n"

// MSG1_RTOS_TASK_CREATE_AFFINITY_SET_RETURN ""
#define MSG1_RTOS_TASK_CREATE_AFFINITY_SET_RETURN 590U
// >>RTOS_MAIN "%N %t xTaskCreateAffinitySet RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG7_RTOS_TASK_CREATE_AFFINITY_SET_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_DELETE_ENTER ""
#define MSG1_RTOS_TASK_DELETE_ENTER 600U
// >>RTOS_MAIN "%N %t vTaskDelete ENTER: xTaskToDelete 0x%08X\n"

// MSG0_RTOS_TASK_DELETE_RETURN ""
#define MSG0_RTOS_TASK_DELETE_RETURN 602U
// >>RTOS_MAIN "%N %t vTaskDelete RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_DELETE_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TASK_DELAY_UNTIL_ENTER ""
#define MSG2_RTOS_TASK_DELAY_UNTIL_ENTER 604U
// >>RTOS_MAIN "%N %t xTaskDelayUntil ENTER: pxPreviousWakeTime 0x%08X, xTimeIncrement %u\n"

// MSG1_RTOS_TASK_DELAY_UNTIL_RETURN ""
#define MSG1_RTOS_TASK_DELAY_UNTIL_RETURN 640U
// >>RTOS_MAIN "%N %t xTaskDelayUntil RETURN: xShouldDelay %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TASK_DELAY_UNTIL_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_DELAY_ENTER ""
#define MSG1_RTOS_TASK_DELAY_ENTER 642U
// >>RTOS_MAIN "%N %t vTaskDelay ENTER: xTicksToDelay %u\n"

// MSG0_RTOS_TASK_DELAY_RETURN ""
#define MSG0_RTOS_TASK_DELAY_RETURN 603U
// >>RTOS_MAIN "%N %t vTaskDelay RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_DELAY_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_GET_STATE_ENTER ""
#define MSG1_RTOS_TASK_GET_STATE_ENTER 644U
// >>RTOS_MAIN "%N %t eTaskGetState ENTER: xTask 0x%08X\n"

// MSG1_RTOS_TASK_GET_STATE_RETURN ""
#define MSG1_RTOS_TASK_GET_STATE_RETURN 646U
// >>RTOS_MAIN "%N %t eTaskGetState RETURN: eReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_GET_STATE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_PRIORITY_GET_ENTER ""
#define MSG1_RTOS_TASK_PRIORITY_GET_ENTER 648U
// >>RTOS_MAIN "%N %t uxTaskPriorityGet ENTER: xTask 0x%08X\n"

// MSG1_RTOS_TASK_PRIORITY_GET_RETURN ""
#define MSG1_RTOS_TASK_PRIORITY_GET_RETURN 650U
// >>RTOS_MAIN "%N %t uxTaskPriorityGet RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_PRIORITY_GET_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_PRIORITY_GET_FROM_ISR_ENTER ""
#define MSG1_RTOS_TASK_PRIORITY_GET_FROM_ISR_ENTER 652U
// >>RTOS_MAIN "%N %t uxTaskPriorityGetFromISR ENTER: xTask 0x%08X\n"

// MSG1_RTOS_TASK_PRIORITY_GET_FROM_ISR_RETURN ""
#define MSG1_RTOS_TASK_PRIORITY_GET_FROM_ISR_RETURN 654U
// >>RTOS_MAIN "%N %t uxTaskPriorityGetFromISR RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_PRIORITY_GET_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_BASE_PRIORITY_GET_ENTER ""
#define MSG1_RTOS_TASK_BASE_PRIORITY_GET_ENTER 656U
// >>RTOS_MAIN "%N %t uxTaskBasePriorityGet ENTER: xTask 0x%08X\n"

// MSG1_RTOS_TASK_BASE_PRIORITY_GET_RETURN ""
#define MSG1_RTOS_TASK_BASE_PRIORITY_GET_RETURN 658U
// >>RTOS_MAIN "%N %t uxTaskBasePriorityGet RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_BASE_PRIORITY_GET_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_BASE_PRIORITY_GET_FROM_ISR_ENTER ""
#define MSG1_RTOS_TASK_BASE_PRIORITY_GET_FROM_ISR_ENTER 660U
// >>RTOS_MAIN "%N %t uxTaskBasePriorityGetFromISR ENTER: xTask 0x%08X\n"

// MSG1_RTOS_TASK_BASE_PRIORITY_GET_FROM_ISR_RETURN ""
#define MSG1_RTOS_TASK_BASE_PRIORITY_GET_FROM_ISR_RETURN 662U
// >>RTOS_MAIN "%N %t uxTaskBasePriorityGetFromISR RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_BASE_PRIORITY_GET_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TASK_PRIORITY_SET_ENTER ""
#define MSG2_RTOS_TASK_PRIORITY_SET_ENTER 664U
// >>RTOS_MAIN "%N %t vTaskPrioritySet ENTER: xTask 0x%08X, uxNewPriority %u\n"

// MSG0_RTOS_TASK_PRIORITY_SET_RETURN ""
#define MSG0_RTOS_TASK_PRIORITY_SET_RETURN 668U
// >>RTOS_MAIN "%N %t vTaskPrioritySet RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TASK_PRIORITY_SET_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TASK_CORE_AFFINITY_SET_ENTER ""
#define MSG2_RTOS_TASK_CORE_AFFINITY_SET_ENTER 672U
// >>RTOS_MAIN "%N %t vTaskCoreAffinitySet ENTER: xTask 0x%08X, uxCoreAffinityMask %u\n"

// MSG0_RTOS_TASK_CORE_AFFINITY_SET_RETURN ""
#define MSG0_RTOS_TASK_CORE_AFFINITY_SET_RETURN 669U
// >>RTOS_MAIN "%N %t vTaskCoreAffinitySet RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TASK_CORE_AFFINITY_SET_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_CORE_AFFINITY_GET_ENTER ""
#define MSG1_RTOS_TASK_CORE_AFFINITY_GET_ENTER 670U
// >>RTOS_MAIN "%N %t vTaskCoreAffinityGet ENTER: xTask 0x%08X\n"

// MSG1_RTOS_TASK_CORE_AFFINITY_GET_RETURN ""
#define MSG1_RTOS_TASK_CORE_AFFINITY_GET_RETURN 676U
// >>RTOS_MAIN "%N %t vTaskCoreAffinityGet RETURN: uxCoreAffinityMask %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_CORE_AFFINITY_GET_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_PREEMPTION_DISABLE_ENTER ""
#define MSG1_RTOS_TASK_PREEMPTION_DISABLE_ENTER 678U
// >>RTOS_MAIN "%N %t vTaskPreemptionDisable ENTER: xTask 0x%08X\n"

// MSG0_RTOS_TASK_PREEMPTION_DISABLE_RETURN ""
#define MSG0_RTOS_TASK_PREEMPTION_DISABLE_RETURN 680U
// >>RTOS_MAIN "%N %t vTaskPreemptionDisable RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_PREEMPTION_DISABLE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_PREEMPTION_ENABLE_ENTER ""
#define MSG1_RTOS_TASK_PREEMPTION_ENABLE_ENTER 682U
// >>RTOS_MAIN "%N %t vTaskPreemptionEnable ENTER: xTask 0x%08X\n"

// MSG0_RTOS_TASK_PREEMPTION_ENABLE_RETURN ""
#define MSG0_RTOS_TASK_PREEMPTION_ENABLE_RETURN 681U
// >>RTOS_MAIN "%N %t vTaskPreemptionEnable RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_PREEMPTION_ENABLE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_SUSPEND_ENTER ""
#define MSG1_RTOS_TASK_SUSPEND_ENTER 684U
// >>RTOS_MAIN "%N %t vTaskSuspend ENTER: xTaskToSuspend 0x%08X\n"

// MSG0_RTOS_TASK_SUSPEND_RETURN ""
#define MSG0_RTOS_TASK_SUSPEND_RETURN 686U
// >>RTOS_MAIN "%N %t vTaskSuspend RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_SUSPEND_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_RESUME_ENTER ""
#define MSG1_RTOS_TASK_RESUME_ENTER 688U
// >>RTOS_MAIN "%N %t vTaskResume ENTER: xTaskToResume 0x%08X\n"

// MSG0_RTOS_TASK_RESUME_RETURN ""
#define MSG0_RTOS_TASK_RESUME_RETURN 687U
// >>RTOS_MAIN "%N %t vTaskResume RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_RESUME_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_RESUME_FROM_ISR_ENTER ""
#define MSG1_RTOS_TASK_RESUME_FROM_ISR_ENTER 690U
// >>RTOS_MAIN "%N %t xTaskResumeFromISR ENTER: xTaskToResume 0x%08X\n"

// MSG1_RTOS_TASK_RESUME_FROM_ISR_RETURN ""
#define MSG1_RTOS_TASK_RESUME_FROM_ISR_RETURN 692U
// >>RTOS_MAIN "%N %t xTaskResumeFromISR RETURN: xYieldRequired %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_RESUME_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG0_RTOS_START_SCHEDULER_ENTER ""
#define MSG0_RTOS_START_SCHEDULER_ENTER 694U
// >>RTOS_MAIN "%N %t vTaskStartScheduler ENTER\n"

// MSG0_RTOS_START_SCHEDULER_RETURN ""
#define MSG0_RTOS_START_SCHEDULER_RETURN 695U
// >>RTOS_MAIN "%N %t vTaskStartScheduler RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_START_SCHEDULER_ENTER](*1e6).3f us\n"

// MSG0_RTOS_END_SCHEDULER_ENTER ""
#define MSG0_RTOS_END_SCHEDULER_ENTER 696U
// >>RTOS_MAIN "%N %t vTaskEndScheduler ENTER\n"

// MSG0_RTOS_END_SCHEDULER_RETURN ""
#define MSG0_RTOS_END_SCHEDULER_RETURN 697U
// >>RTOS_MAIN "%N %t vTaskEndScheduler RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_END_SCHEDULER_ENTER](*1e6).3f us\n"

// MSG0_RTOS_SUSPEND_ALL_ENTER ""
#define MSG0_RTOS_SUSPEND_ALL_ENTER 698U
// >>RTOS_MAIN "%N %t vTaskSuspendAll ENTER\n"

// MSG0_RTOS_SUSPEND_ALL_RETURN ""
#define MSG0_RTOS_SUSPEND_ALL_RETURN 699U
// >>RTOS_MAIN "%N %t vTaskSuspendAll RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_SUSPEND_ALL_ENTER](*1e6).3f us\n"

// MSG0_RTOS_RESUME_ALL_ENTER ""
#define MSG0_RTOS_RESUME_ALL_ENTER 700U
// >>RTOS_MAIN "%N %t xTaskResumeAll ENTER\n"

// MSG1_RTOS_RESUME_ALL_RETURN ""
#define MSG1_RTOS_RESUME_ALL_RETURN 702U
// >>RTOS_MAIN "%N %t xTaskResumeAll RETURN: xAlreadyYielded %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_RESUME_ALL_ENTER](*1e6).3f us\n"

// MSG0_RTOS_GET_TICK_COUNT_ENTER ""
#define MSG0_RTOS_GET_TICK_COUNT_ENTER 701U
// >>RTOS_MAIN "%N %t xTaskGetTickCount ENTER\n"

// MSG1_RTOS_GET_TICK_COUNT_RETURN ""
#define MSG1_RTOS_GET_TICK_COUNT_RETURN 704U
// >>RTOS_MAIN "%N %t xTaskGetTickCount RETURN: xTicks %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_GET_TICK_COUNT_ENTER](*1e6).3f us\n"

// MSG0_RTOS_GET_TICK_COUNT_FROM_ISR_ENTER ""
#define MSG0_RTOS_GET_TICK_COUNT_FROM_ISR_ENTER 706U
// >>RTOS_MAIN "%N %t xTaskGetTickCountFromISR ENTER\n"

// MSG1_RTOS_GET_TICK_COUNT_FROM_ISR_RETURN ""
#define MSG1_RTOS_GET_TICK_COUNT_FROM_ISR_RETURN 708U
// >>RTOS_MAIN "%N %t xTaskGetTickCountFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_GET_TICK_COUNT_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG0_RTOS_GET_NUMBER_OF_TASKS_ENTER ""
#define MSG0_RTOS_GET_NUMBER_OF_TASKS_ENTER 707U
// >>RTOS_MAIN "%N %t uxTaskGetNumberOfTasks ENTER\n"

// MSG1_RTOS_GET_NUMBER_OF_TASKS_RETURN ""
#define MSG1_RTOS_GET_NUMBER_OF_TASKS_RETURN 710U
// >>RTOS_MAIN "%N %t uxTaskGetNumberOfTasks RETURN: uxCurrentNumberOfTasks %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_GET_NUMBER_OF_TASKS_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_GET_NAME_ENTER ""
#define MSG1_RTOS_TASK_GET_NAME_ENTER 712U
// >>RTOS_MAIN "%N %t pcTaskGetName ENTER: xTaskToQuery 0x%08X\n"

// MSG1_RTOS_TASK_GET_NAME_RETURN ""
#define MSG1_RTOS_TASK_GET_NAME_RETURN 714U
// >>RTOS_MAIN "%N %t pcTaskGetName RETURN: pcTaskName 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_GET_NAME_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TASK_GET_HANDLE_ENTER ""
#define MSG1_RTOS_TASK_GET_HANDLE_ENTER 716U
// >>RTOS_MAIN "%N %t xTaskGetHandle ENTER: pcNameToQuery 0x%08X\n"

// MSG1_RTOS_TASK_GET_HANDLE_RETURN ""
#define MSG1_RTOS_TASK_GET_HANDLE_RETURN 718U
// >>RTOS_MAIN "%N %t xTaskGetHandle RETURN: pxTCB 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TASK_GET_HANDLE_ENTER](*1e6).3f us\n"

// MSG3_RTOS_TASK_GET_STATIC_BUFFERS_ENTER ""
#define MSG3_RTOS_TASK_GET_STATIC_BUFFERS_ENTER 720U
// >>RTOS_MAIN "%N %t xTaskGetStaticBuffers ENTER: xTask 0x%08X, ppuxStackBuffer 0x%08X, "
// >>RTOS_MAIN "ppxTaskBuffer 0x%08X\n"

// MSG1_RTOS_TASK_GET_STATIC_BUFFERS_RETURN ""
#define MSG1_RTOS_TASK_GET_STATIC_BUFFERS_RETURN 728U
// >>RTOS_MAIN "%N %t xTaskGetStaticBuffers RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_TASK_GET_STATIC_BUFFERS_ENTER](*1e6).3f us\n"

// MSG3_RTOS_TASK_GET_SYSTEM_STATE_ENTER ""
#define MSG3_RTOS_TASK_GET_SYSTEM_STATE_ENTER 736U
// >>RTOS_MAIN "%N %t uxTaskGetSystemState ENTER: pxTaskStatusArray 0x%08X, "
// >>RTOS_MAIN "uxArraySize %u, pulTotalRunTime 0x%08X\n"

// MSG1_RTOS_TASK_GET_SYSTEM_STATE_RETURN ""
#define MSG1_RTOS_TASK_GET_SYSTEM_STATE_RETURN 730U
// >>RTOS_MAIN "%N %t uxTaskGetSystemState RETURN: uxTask 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_TASK_GET_SYSTEM_STATE_ENTER](*1e6).3f us\n"

// MSG0_RTOS_GET_IDLE_TASK_HANDLE_ENTER ""
#define MSG0_RTOS_GET_IDLE_TASK_HANDLE_ENTER 732U
// >>RTOS_MAIN "%N %t xTaskGetIdleTaskHandle ENTER\n"

// MSG1_RTOS_GET_IDLE_TASK_HANDLE_RETURN ""
#define MSG1_RTOS_GET_IDLE_TASK_HANDLE_RETURN 734U
// >>RTOS_MAIN "%N %t xTaskGetIdleTaskHandle RETURN: xIdleTaskHandle 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_GET_IDLE_TASK_HANDLE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_IDLE_TASK_HANDLE_FOR_CORE_ENTER ""
#define MSG1_RTOS_GET_IDLE_TASK_HANDLE_FOR_CORE_ENTER 744U
// >>RTOS_MAIN "%N %t xTaskGetIdleTaskHandleForCore ENTER: xCoreID %u\n"

// MSG1_RTOS_GET_IDLE_TASK_HANDLE_FOR_CORE_RETURN ""
#define MSG1_RTOS_GET_IDLE_TASK_HANDLE_FOR_CORE_RETURN 746U
// >>RTOS_MAIN "%N %t xTaskGetIdleTaskHandleForCore RETURN: xIdleTaskHandle 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_IDLE_TASK_HANDLE_FOR_CORE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STEP_TICK_ENTER ""
#define MSG1_RTOS_STEP_TICK_ENTER 748U
// >>RTOS_MAIN "%N %t vTaskStepTick ENTER: xTicksToJump %u\n"

// MSG0_RTOS_STEP_TICK_RETURN ""
#define MSG0_RTOS_STEP_TICK_RETURN 733U
// >>RTOS_MAIN "%N %t vTaskStepTick RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STEP_TICK_ENTER](*1e6).3f us\n"

// MSG1_RTOS_CATCH_UP_TICKS_ENTER ""
#define MSG1_RTOS_CATCH_UP_TICKS_ENTER 750U
// >>RTOS_MAIN "%N %t xTaskCatchUpTicks ENTER: xTicksToCatchUp %u\n"

// MSG1_RTOS_CATCH_UP_TICKS_RETURN ""
#define MSG1_RTOS_CATCH_UP_TICKS_RETURN 752U
// >>RTOS_MAIN "%N %t xTaskCatchUpTicks RETURN: xYieldOccurred %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_CATCH_UP_TICKS_ENTER](*1e6).3f us\n"

// MSG1_RTOS_ABORT_DELAY_ENTER ""
#define MSG1_RTOS_ABORT_DELAY_ENTER 754U
// >>RTOS_MAIN "%N %t xTaskAbortDelay ENTER: xTask 0x%08X\n"

// MSG1_RTOS_ABORT_DELAY_RETURN ""
#define MSG1_RTOS_ABORT_DELAY_RETURN 756U
// >>RTOS_MAIN "%N %t xTaskAbortDelay RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_ABORT_DELAY_ENTER](*1e6).3f us\n"

// MSG0_RTOS_INCREMENT_TICK_ENTER ""
#define MSG0_RTOS_INCREMENT_TICK_ENTER 758U
// >>RTOS_MAIN "%N %t xTaskIncrementTick ENTER\n"

// MSG1_RTOS_INCREMENT_TICK_RETURN ""
#define MSG1_RTOS_INCREMENT_TICK_RETURN 760U
// >>RTOS_MAIN "%N %t xTaskIncrementTick RETURN: xSwitchRequired %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_INCREMENT_TICK_ENTER](*1e6).3f us\n"

// MSG2_RTOS_SET_APPLICATION_TASK_TAG_ENTER ""
#define MSG2_RTOS_SET_APPLICATION_TASK_TAG_ENTER 764U
// >>RTOS_MAIN "%N %t vTaskSetApplicationTaskTag ENTER: xTask 0x%08X, pxHookFunction 0x%08X\n"

// MSG0_RTOS_SET_APPLICATION_TASK_TAG_RETURN ""
#define MSG0_RTOS_SET_APPLICATION_TASK_TAG_RETURN 759U
// >>RTOS_MAIN "%N %t vTaskSetApplicationTaskTag RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_SET_APPLICATION_TASK_TAG_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_APPLICATION_TASK_TAG_ENTER ""
#define MSG1_RTOS_GET_APPLICATION_TASK_TAG_ENTER 762U
// >>RTOS_MAIN "%N %t xTaskGetApplicationTaskTag ENTER: xTask 0x%08X\n"

// MSG1_RTOS_GET_APPLICATION_TASK_TAG_RETURN ""
#define MSG1_RTOS_GET_APPLICATION_TASK_TAG_RETURN 768U
// >>RTOS_MAIN "%N %t xTaskGetApplicationTaskTag RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_APPLICATION_TASK_TAG_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_APPLICATION_TASK_TAG_FROM_ISR_ENTER ""
#define MSG1_RTOS_GET_APPLICATION_TASK_TAG_FROM_ISR_ENTER 770U
// >>RTOS_MAIN "%N %t xTaskGetApplicationTaskTagFromISR ENTER: xTask 0x%08X\n"

// MSG1_RTOS_GET_APPLICATION_TASK_TAG_FROM_ISR_RETURN ""
#define MSG1_RTOS_GET_APPLICATION_TASK_TAG_FROM_ISR_RETURN 772U
// >>RTOS_MAIN "%N %t xTaskGetApplicationTaskTagFromISR RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_APPLICATION_TASK_TAG_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_CALL_APPLICATION_TASK_HOOK_ENTER ""
#define MSG2_RTOS_CALL_APPLICATION_TASK_HOOK_ENTER 776U
// >>RTOS_MAIN "%N %t xTaskCallApplicationTaskHook ENTER: xTask 0x%08X, pvParameter 0x%08X\n"

// MSG1_RTOS_CALL_APPLICATION_TASK_HOOK_RETURN ""
#define MSG1_RTOS_CALL_APPLICATION_TASK_HOOK_RETURN 774U
// >>RTOS_MAIN "%N %t xTaskCallApplicationTaskHook RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_CALL_APPLICATION_TASK_HOOK_ENTER](*1e6).3f us\n"

// MSG0_RTOS_SWITCH_CONTEXT_ENTER ""
#define MSG0_RTOS_SWITCH_CONTEXT_ENTER 780U
// >>RTOS_MAIN "%N %t vTaskSwitchContext ENTER\n"

// MSG0_RTOS_SWITCH_CONTEXT_RETURN ""
#define MSG0_RTOS_SWITCH_CONTEXT_RETURN 781U
// >>RTOS_MAIN "%N %t vTaskSwitchContext RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_SWITCH_CONTEXT_ENTER](*1e6).3f us\n"

// MSG2_RTOS_PLACE_ON_EVENT_LIST_ENTER ""
#define MSG2_RTOS_PLACE_ON_EVENT_LIST_ENTER 784U
// >>RTOS_MAIN "%N %t vTaskPlaceOnEventList ENTER: pxEventList 0x%08X, xTicksToWait %u\n"

// MSG0_RTOS_PLACE_ON_EVENT_LIST_RETURN ""
#define MSG0_RTOS_PLACE_ON_EVENT_LIST_RETURN 782U
// >>RTOS_MAIN "%N %t vTaskPlaceOnEventList RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_PLACE_ON_EVENT_LIST_ENTER](*1e6).3f us\n"

// MSG3_RTOS_PLACE_ON_UNORDERED_EVENT_LIST_ENTER ""
#define MSG3_RTOS_PLACE_ON_UNORDERED_EVENT_LIST_ENTER 792U
// >>RTOS_MAIN "%N %t vTaskPlaceOnUnorderedEventList ENTER: pxEventList 0x%08X, "
// >>RTOS_MAIN "xItemValue %u, xTicksToWait %u\n"

// MSG0_RTOS_PLACE_ON_UNORDERED_EVENT_LIST_RETURN ""
#define MSG0_RTOS_PLACE_ON_UNORDERED_EVENT_LIST_RETURN 783U
// >>RTOS_MAIN "%N %t vTaskPlaceOnUnorderedEventList RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_PLACE_ON_UNORDERED_EVENT_LIST_ENTER](*1e6).3f us\n"

// MSG3_RTOS_PLACE_ON_EVENT_LIST_RESTRICTED_ENTER ""
#define MSG3_RTOS_PLACE_ON_EVENT_LIST_RESTRICTED_ENTER 800U
// >>RTOS_MAIN "%N %t vTaskPlaceOnEventListRestricted ENTER: pxEventList 0x%08X, "
// >>RTOS_MAIN "xTicksToWait %u, xWaitIndefinitely %u\n"

// MSG0_RTOS_PLACE_ON_EVENT_LIST_RESTRICTED_RETURN ""
#define MSG0_RTOS_PLACE_ON_EVENT_LIST_RESTRICTED_RETURN 788U
// >>RTOS_MAIN "%N %t vTaskPlaceOnEventListRestricted RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_PLACE_ON_EVENT_LIST_RESTRICTED_ENTER](*1e6).3f us\n"

// MSG1_RTOS_REMOVE_FROM_EVENT_LIST_ENTER ""
#define MSG1_RTOS_REMOVE_FROM_EVENT_LIST_ENTER 790U
// >>RTOS_MAIN "%N %t xTaskRemoveFromEventList ENTER: pxEventList 0x%08X\n"

// MSG1_RTOS_REMOVE_FROM_EVENT_LIST_RETURN ""
#define MSG1_RTOS_REMOVE_FROM_EVENT_LIST_RETURN 808U
// >>RTOS_MAIN "%N %t xTaskRemoveFromEventList RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_REMOVE_FROM_EVENT_LIST_ENTER](*1e6).3f us\n"

// MSG2_RTOS_REMOVE_FROM_UNORDERED_EVENT_LIST_ENTER ""
#define MSG2_RTOS_REMOVE_FROM_UNORDERED_EVENT_LIST_ENTER 812U
// >>RTOS_MAIN "%N %t vTaskRemoveFromUnorderedEventList ENTER: pxEventListItem 0x%08X, xItemValue %u\n"

// MSG0_RTOS_REMOVE_FROM_UNORDERED_EVENT_LIST_RETURN ""
#define MSG0_RTOS_REMOVE_FROM_UNORDERED_EVENT_LIST_RETURN 789U
// >>RTOS_MAIN "%N %t vTaskRemoveFromUnorderedEventList RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_REMOVE_FROM_UNORDERED_EVENT_LIST_ENTER](*1e6).3f us\n"

// MSG1_RTOS_SET_TIME_OUT_STATE_ENTER ""
#define MSG1_RTOS_SET_TIME_OUT_STATE_ENTER 810U
// >>RTOS_MAIN "%N %t vTaskSetTimeOutState ENTER: pxTimeOut 0x%08X\n"

// MSG0_RTOS_SET_TIME_OUT_STATE_RETURN ""
#define MSG0_RTOS_SET_TIME_OUT_STATE_RETURN 816U
// >>RTOS_MAIN "%N %t vTaskSetTimeOutState RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_SET_TIME_OUT_STATE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_INTERNAL_SET_TIME_OUT_STATE_ENTER ""
#define MSG1_RTOS_INTERNAL_SET_TIME_OUT_STATE_ENTER 818U
// >>RTOS_MAIN "%N %t vTaskInternalSetTimeOutState ENTER: pxTimeOut 0x%08X\n"

// MSG0_RTOS_INTERNAL_SET_TIME_OUT_STATE_RETURN ""
#define MSG0_RTOS_INTERNAL_SET_TIME_OUT_STATE_RETURN 817U
// >>RTOS_MAIN "%N %t vTaskInternalSetTimeOutState RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_INTERNAL_SET_TIME_OUT_STATE_ENTER](*1e6).3f us\n"

// MSG2_RTOS_CHECK_FOR_TIME_OUT_ENTER ""
#define MSG2_RTOS_CHECK_FOR_TIME_OUT_ENTER 820U
// >>RTOS_MAIN "%N %t xTaskCheckForTimeOut ENTER: pxTimeOut 0x%08X, pxTicksToWait 0x%08X\n"

// MSG1_RTOS_CHECK_FOR_TIME_OUT_RETURN ""
#define MSG1_RTOS_CHECK_FOR_TIME_OUT_RETURN 824U
// >>RTOS_MAIN "%N %t xTaskCheckForTimeOut RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_CHECK_FOR_TIME_OUT_ENTER](*1e6).3f us\n"

// MSG0_RTOS_MISSED_YIELD_ENTER ""
#define MSG0_RTOS_MISSED_YIELD_ENTER 826U
// >>RTOS_MAIN "%N %t vTaskMissedYield ENTER\n"

// MSG0_RTOS_MISSED_YIELD_RETURN ""
#define MSG0_RTOS_MISSED_YIELD_RETURN 827U
// >>RTOS_MAIN "%N %t vTaskMissedYield RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_MISSED_YIELD_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_TASK_NUMBER_ENTER ""
#define MSG1_RTOS_GET_TASK_NUMBER_ENTER 828U
// >>RTOS_MAIN "%N %t uxTaskGetTaskNumber ENTER: xTask 0x%08X\n"

// MSG1_RTOS_GET_TASK_NUMBER_RETURN ""
#define MSG1_RTOS_GET_TASK_NUMBER_RETURN 830U
// >>RTOS_MAIN "%N %t uxTaskGetTaskNumber RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_TASK_NUMBER_ENTER](*1e6).3f us\n"

// MSG2_RTOS_SET_TASK_NUMBER_ENTER ""
#define MSG2_RTOS_SET_TASK_NUMBER_ENTER 832U
// >>RTOS_MAIN "%N %t vTaskSetTaskNumber ENTER: xTask 0x%08X, uxHandle 0x%08X\n"

// MSG0_RTOS_SET_TASK_NUMBER_RETURN ""
#define MSG0_RTOS_SET_TASK_NUMBER_RETURN 836U
// >>RTOS_MAIN "%N %t vTaskSetTaskNumber RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_SET_TASK_NUMBER_ENTER](*1e6).3f us\n"

// MSG0_RTOS_CONFIRM_SLEEP_MODE_STATUS_ENTER ""
#define MSG0_RTOS_CONFIRM_SLEEP_MODE_STATUS_ENTER 837U
// >>RTOS_MAIN "%N %t eTaskConfirmSleepModeStatus ENTER\n"

// MSG1_RTOS_CONFIRM_SLEEP_MODE_STATUS_RETURN ""
#define MSG1_RTOS_CONFIRM_SLEEP_MODE_STATUS_RETURN 838U
// >>RTOS_MAIN "%N %t eTaskConfirmSleepModeStatus RETURN: eReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_CONFIRM_SLEEP_MODE_STATUS_ENTER](*1e6).3f us\n"

// MSG3_RTOS_SET_THREAD_LOCAL_STORAGE_POINTER_ENTER ""
#define MSG3_RTOS_SET_THREAD_LOCAL_STORAGE_POINTER_ENTER 840U
// >>RTOS_MAIN "%N %t vTaskSetThreadLocalStoragePointer ENTER: xTaskToSet 0x%08X, "
// >>RTOS_MAIN "xIndex %u, pvValue 0x%08X\n"

// MSG0_RTOS_SET_THREAD_LOCAL_STORAGE_POINTER_RETURN ""
#define MSG0_RTOS_SET_THREAD_LOCAL_STORAGE_POINTER_RETURN 848U
// >>RTOS_MAIN "%N %t vTaskSetThreadLocalStoragePointer RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_SET_THREAD_LOCAL_STORAGE_POINTER_ENTER](*1e6).3f us\n"

// MSG2_RTOS_GET_THREAD_LOCAL_STORAGE_POINTER_ENTER ""
#define MSG2_RTOS_GET_THREAD_LOCAL_STORAGE_POINTER_ENTER 852U
// >>RTOS_MAIN "%N %t pvTaskGetThreadLocalStoragePointer ENTER: xTaskToQuery 0x%08X, xIndex %u\n"

// MSG1_RTOS_GET_THREAD_LOCAL_STORAGE_POINTER_RETURN ""
#define MSG1_RTOS_GET_THREAD_LOCAL_STORAGE_POINTER_RETURN 850U
// >>RTOS_MAIN "%N %t pvTaskGetThreadLocalStoragePointer RETURN: pvReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_GET_THREAD_LOCAL_STORAGE_POINTER_ENTER](*1e6).3f us\n"

// MSG2_RTOS_ALLOCATE_MPU_REGIONS_ENTER ""
#define MSG2_RTOS_ALLOCATE_MPU_REGIONS_ENTER 856U
// >>RTOS_MAIN "%N %t vTaskAllocateMPURegions ENTER: xTaskToModify 0x%08X, pxRegions 0x%08X\n"

// MSG0_RTOS_ALLOCATE_MPU_REGIONS_RETURN ""
#define MSG0_RTOS_ALLOCATE_MPU_REGIONS_RETURN 849U
// >>RTOS_MAIN "%N %t vTaskAllocateMPURegions RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_ALLOCATE_MPU_REGIONS_ENTER](*1e6).3f us\n"

// MSG4_RTOS_TASK_GET_INFO_ENTER ""
#define MSG4_RTOS_TASK_GET_INFO_ENTER 864U
// >>RTOS_MAIN "%N %t vTaskGetInfo ENTER: xTask 0x%08X, pxTaskStatus 0x%08X, "
// >>RTOS_MAIN "xGetFreeStackSpace %u, eState %u\n"

// MSG0_RTOS_TASK_GET_INFO_RETURN ""
#define MSG0_RTOS_TASK_GET_INFO_RETURN 860U
// >>RTOS_MAIN "%N %t vTaskGetInfo RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_TASK_GET_INFO_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_STACK_HIGH_WATER_MARK2_ENTER ""
#define MSG1_RTOS_GET_STACK_HIGH_WATER_MARK2_ENTER 862U
// >>RTOS_MAIN "%N %t uxTaskGetStackHighWaterMark2 ENTER: xTask 0x%08X\n"

// MSG1_RTOS_GET_STACK_HIGH_WATER_MARK2_RETURN ""
#define MSG1_RTOS_GET_STACK_HIGH_WATER_MARK2_RETURN 880U
// >>RTOS_MAIN "%N %t uxTaskGetStackHighWaterMark2 RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_STACK_HIGH_WATER_MARK2_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_STACK_HIGH_WATER_MARK_ENTER ""
#define MSG1_RTOS_GET_STACK_HIGH_WATER_MARK_ENTER 882U
// >>RTOS_MAIN "%N %t uxTaskGetStackHighWaterMark ENTER: xTask 0x%08X\n"

// MSG1_RTOS_GET_STACK_HIGH_WATER_MARK_RETURN ""
#define MSG1_RTOS_GET_STACK_HIGH_WATER_MARK_RETURN 884U
// >>RTOS_MAIN "%N %t uxTaskGetStackHighWaterMark RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_STACK_HIGH_WATER_MARK_ENTER](*1e6).3f us\n"

// MSG0_RTOS_GET_CURRENT_TASK_HANDLE_ENTER ""
#define MSG0_RTOS_GET_CURRENT_TASK_HANDLE_ENTER 861U
// >>RTOS_MAIN "%N %t xTaskGetCurrentTaskHandle ENTER\n"

// MSG1_RTOS_GET_CURRENT_TASK_HANDLE_RETURN ""
#define MSG1_RTOS_GET_CURRENT_TASK_HANDLE_RETURN 886U
// >>RTOS_MAIN "%N %t xTaskGetCurrentTaskHandle RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_GET_CURRENT_TASK_HANDLE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_CURRENT_TASK_HANDLE_FOR_CORE_ENTER ""
#define MSG1_RTOS_GET_CURRENT_TASK_HANDLE_FOR_CORE_ENTER 888U
// >>RTOS_MAIN "%N %t xTaskGetCurrentTaskHandleForCore ENTER: xCoreID %u\n"

// MSG1_RTOS_GET_CURRENT_TASK_HANDLE_FOR_CORE_RETURN ""
#define MSG1_RTOS_GET_CURRENT_TASK_HANDLE_FOR_CORE_RETURN 890U
// >>RTOS_MAIN "%N %t xTaskGetCurrentTaskHandleForCore RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_CURRENT_TASK_HANDLE_FOR_CORE_ENTER](*1e6).3f us\n"

// MSG0_RTOS_GET_SCHEDULER_STATE_ENTER ""
#define MSG0_RTOS_GET_SCHEDULER_STATE_ENTER 892U
// >>RTOS_MAIN "%N %t xTaskGetSchedulerState ENTER\n"

// MSG1_RTOS_GET_SCHEDULER_STATE_RETURN ""
#define MSG1_RTOS_GET_SCHEDULER_STATE_RETURN 894U
// >>RTOS_MAIN "%N %t xTaskGetSchedulerState RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_GET_SCHEDULER_STATE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_PRIORITY_INHERIT_ENTER ""
#define MSG1_RTOS_PRIORITY_INHERIT_ENTER 896U
// >>RTOS_MAIN "%N %t xTaskPriorityInherit ENTER: pxMutexHolder 0x%08X\n"

// MSG1_RTOS_PRIORITY_INHERIT_RETURN ""
#define MSG1_RTOS_PRIORITY_INHERIT_RETURN 898U
// >>RTOS_MAIN "%N %t xTaskPriorityInherit RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_PRIORITY_INHERIT_ENTER](*1e6).3f us\n"

// MSG1_RTOS_PRIORITY_DISINHERIT_ENTER ""
#define MSG1_RTOS_PRIORITY_DISINHERIT_ENTER 900U
// >>RTOS_MAIN "%N %t xTaskPriorityDisinherit ENTER: pxMutexHolder 0x%08X\n"

// MSG1_RTOS_PRIORITY_DISINHERIT_RETURN ""
#define MSG1_RTOS_PRIORITY_DISINHERIT_RETURN 902U
// >>RTOS_MAIN "%N %t xTaskPriorityDisinherit RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_PRIORITY_DISINHERIT_ENTER](*1e6).3f us\n"

// MSG2_RTOS_PRIORITY_DISINHERIT_AFTER_TIMEOUT_ENTER ""
#define MSG2_RTOS_PRIORITY_DISINHERIT_AFTER_TIMEOUT_ENTER 904U
// >>RTOS_MAIN "%N %t vTaskPriorityDisinheritAfterTimeout ENTER: pxMutexHolder 0x%08X, "
// >>RTOS_MAIN "uxHighestPriorityWaitingTask 0x%08X\n"

// MSG0_RTOS_PRIORITY_DISINHERIT_AFTER_TIMEOUT_RETURN ""
#define MSG0_RTOS_PRIORITY_DISINHERIT_AFTER_TIMEOUT_RETURN 893U
// >>RTOS_MAIN "%N %t vTaskPriorityDisinheritAfterTimeout RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_PRIORITY_DISINHERIT_AFTER_TIMEOUT_ENTER](*1e6).3f us\n"

// MSG0_RTOS_YIELD_WITHIN_API_ENTER ""
#define MSG0_RTOS_YIELD_WITHIN_API_ENTER 908U
// >>RTOS_MAIN "%N %t vTaskYieldWithinAPI ENTER\n"

// MSG0_RTOS_YIELD_WITHIN_API_RETURN ""
#define MSG0_RTOS_YIELD_WITHIN_API_RETURN 909U
// >>RTOS_MAIN "%N %t vTaskYieldWithinAPI RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_YIELD_WITHIN_API_ENTER](*1e6).3f us\n"

// MSG0_RTOS_ENTER_CRITICAL_ENTER ""
#define MSG0_RTOS_ENTER_CRITICAL_ENTER 910U
// >>RTOS_MAIN "%N %t vTaskEnterCritical ENTER\n"

// MSG0_RTOS_ENTER_CRITICAL_RETURN ""
#define MSG0_RTOS_ENTER_CRITICAL_RETURN 911U
// >>RTOS_MAIN "%N %t vTaskEnterCritical RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_ENTER_CRITICAL_ENTER](*1e6).3f us\n"

// MSG0_RTOS_ENTER_CRITICAL_FROM_ISR_ENTER ""
#define MSG0_RTOS_ENTER_CRITICAL_FROM_ISR_ENTER 912U
// >>RTOS_MAIN "%N %t vTaskEnterCriticalFromISR ENTER\n"

// MSG1_RTOS_ENTER_CRITICAL_FROM_ISR_RETURN ""
#define MSG1_RTOS_ENTER_CRITICAL_FROM_ISR_RETURN 914U
// >>RTOS_MAIN "%N %t vTaskEnterCriticalFromISR RETURN: uxSavedInterruptStatus %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_ENTER_CRITICAL_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG0_RTOS_EXIT_CRITICAL_ENTER ""
#define MSG0_RTOS_EXIT_CRITICAL_ENTER 913U
// >>RTOS_MAIN "%N %t vTaskExitCritical ENTER\n"

// MSG0_RTOS_EXIT_CRITICAL_RETURN ""
#define MSG0_RTOS_EXIT_CRITICAL_RETURN 916U
// >>RTOS_MAIN "%N %t vTaskExitCritical RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_EXIT_CRITICAL_ENTER](*1e6).3f us\n"

// MSG1_RTOS_EXIT_CRITICAL_FROM_ISR_ENTER ""
#define MSG1_RTOS_EXIT_CRITICAL_FROM_ISR_ENTER 918U
// >>RTOS_MAIN "%N %t vTaskExitCriticalFromISR ENTER: uxSavedInterruptStatus %u\n"

// MSG0_RTOS_EXIT_CRITICAL_FROM_ISR_RETURN ""
#define MSG0_RTOS_EXIT_CRITICAL_FROM_ISR_RETURN 917U
// >>RTOS_MAIN "%N %t vTaskExitCriticalFromISR RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_EXIT_CRITICAL_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_LIST_TASKS_ENTER ""
#define MSG2_RTOS_LIST_TASKS_ENTER 920U
// >>RTOS_MAIN "%N %t vTaskListTasks ENTER: pcWriteBuffer 0x%08X, uxBufferLength %u\n"

// MSG0_RTOS_LIST_TASKS_RETURN ""
#define MSG0_RTOS_LIST_TASKS_RETURN 924U
// >>RTOS_MAIN "%N %t vTaskListTasks RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_LIST_TASKS_ENTER](*1e6).3f us\n"

// MSG2_RTOS_GET_RUN_TIME_STATISTICS_ENTER ""
#define MSG2_RTOS_GET_RUN_TIME_STATISTICS_ENTER 928U
// >>RTOS_MAIN "%N %t vTaskGetRunTimeStatistics ENTER: pcWriteBuffer 0x%08X, uxBufferLength %u\n"

// MSG0_RTOS_GET_RUN_TIME_STATISTICS_RETURN ""
#define MSG0_RTOS_GET_RUN_TIME_STATISTICS_RETURN 925U
// >>RTOS_MAIN "%N %t vTaskGetRunTimeStatistics RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_GET_RUN_TIME_STATISTICS_ENTER](*1e6).3f us\n"

// MSG0_RTOS_RESET_EVENT_ITEM_VALUE_ENTER ""
#define MSG0_RTOS_RESET_EVENT_ITEM_VALUE_ENTER 926U
// >>RTOS_MAIN "%N %t uxTaskResetEventItemValue ENTER\n"

// MSG1_RTOS_RESET_EVENT_ITEM_VALUE_RETURN ""
#define MSG1_RTOS_RESET_EVENT_ITEM_VALUE_RETURN 932U
// >>RTOS_MAIN "%N %t uxTaskResetEventItemValue RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_RESET_EVENT_ITEM_VALUE_ENTER](*1e6).3f us\n"

// MSG0_RTOS_INCREMENT_MUTEX_HELD_COUNT_ENTER ""
#define MSG0_RTOS_INCREMENT_MUTEX_HELD_COUNT_ENTER 927U
// >>RTOS_MAIN "%N %t pvTaskIncrementMutexHeldCount ENTER\n"

// MSG1_RTOS_INCREMENT_MUTEX_HELD_COUNT_RETURN ""
#define MSG1_RTOS_INCREMENT_MUTEX_HELD_COUNT_RETURN 934U
// >>RTOS_MAIN "%N %t pvTaskIncrementMutexHeldCount RETURN: pxTCB 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_INCREMENT_MUTEX_HELD_COUNT_ENTER](*1e6).3f us\n"

// MSG3_RTOS_GENERIC_NOTIFY_TAKE_ENTER ""
#define MSG3_RTOS_GENERIC_NOTIFY_TAKE_ENTER 936U
// >>RTOS_MAIN "%N %t ulTaskGenericNotifyTake ENTER: uxIndexToWaitOn %u, "
// >>RTOS_MAIN "xClearCountOnExit %u, xTicksToWait %u\n"

// MSG1_RTOS_GENERIC_NOTIFY_TAKE_RETURN ""
#define MSG1_RTOS_GENERIC_NOTIFY_TAKE_RETURN 944U
// >>RTOS_MAIN "%N %t ulTaskGenericNotifyTake RETURN: ulReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_GENERIC_NOTIFY_TAKE_ENTER](*1e6).3f us\n"

// MSG5_RTOS_GENERIC_NOTIFY_WAIT_ENTER ""
#define MSG5_RTOS_GENERIC_NOTIFY_WAIT_ENTER 960U
// >>RTOS_MAIN "%N %t xTaskGenericNotifyWait ENTER: uxIndexToWaitOn %u, ulBitsToClearOnEntry 0x%08X, "
// >>RTOS_MAIN "ulBitsToClearOnExit 0x%08X, pulNotificationValue 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_GENERIC_NOTIFY_WAIT_RETURN ""
#define MSG1_RTOS_GENERIC_NOTIFY_WAIT_RETURN 946U
// >>RTOS_MAIN "%N %t xTaskGenericNotifyWait RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG5_RTOS_GENERIC_NOTIFY_WAIT_ENTER](*1e6).3f us\n"

// MSG5_RTOS_GENERIC_NOTIFY_ENTER ""
#define MSG5_RTOS_GENERIC_NOTIFY_ENTER 976U
// >>RTOS_MAIN "%N %t xTaskGenericNotify ENTER: xTaskToNotify 0x%08X, uxIndexToNotify %u, "
// >>RTOS_MAIN "ulValue %u, eAction %u, pulPreviousNotificationValue 0x%08X\n"

// MSG1_RTOS_GENERIC_NOTIFY_RETURN ""
#define MSG1_RTOS_GENERIC_NOTIFY_RETURN 948U
// >>RTOS_MAIN "%N %t xTaskGenericNotify RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG5_RTOS_GENERIC_NOTIFY_ENTER](*1e6).3f us\n"

// MSG6_RTOS_GENERIC_NOTIFY_FROM_ISR_ENTER ""
#define MSG6_RTOS_GENERIC_NOTIFY_FROM_ISR_ENTER 992U
// >>RTOS_MAIN "%N %t xTaskGenericNotifyFromISR ENTER: xTaskToNotify 0x%08X, uxIndexToNotify %u, "
// >>RTOS_MAIN "ulValue %u, eAction %u, pulPreviousNotificationValue %u, pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_GENERIC_NOTIFY_FROM_ISR_RETURN ""
#define MSG1_RTOS_GENERIC_NOTIFY_FROM_ISR_RETURN 950U
// >>RTOS_MAIN "%N %t xTaskGenericNotifyFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG6_RTOS_GENERIC_NOTIFY_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG3_RTOS_GENERIC_NOTIFY_GIVE_FROM_ISR_ENTER ""
#define MSG3_RTOS_GENERIC_NOTIFY_GIVE_FROM_ISR_ENTER 952U
// >>RTOS_MAIN "%N %t vTaskGenericNotifyGiveFromISR ENTER: xTaskToNotify 0x%08X, uxIndexToNotify %u, "
// >>RTOS_MAIN "pxHigherPriorityTaskWoken 0x%08X\n"

// MSG0_RTOS_GENERIC_NOTIFY_GIVE_FROM_ISR_RETURN ""
#define MSG0_RTOS_GENERIC_NOTIFY_GIVE_FROM_ISR_RETURN 1008U
// >>RTOS_MAIN "%N %t vTaskGenericNotifyGiveFromISR RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_GENERIC_NOTIFY_GIVE_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_GENERIC_NOTIFY_STATE_CLEAR_ENTER ""
#define MSG2_RTOS_GENERIC_NOTIFY_STATE_CLEAR_ENTER 1012U
// >>RTOS_MAIN "%N %t xTaskGenericNotifyStateClear ENTER: xTask 0x%08X, uxIndexToClear %u\n"

// MSG1_RTOS_GENERIC_NOTIFY_STATE_CLEAR_RETURN ""
#define MSG1_RTOS_GENERIC_NOTIFY_STATE_CLEAR_RETURN 1010U
// >>RTOS_MAIN "%N %t xTaskGenericNotifyStateClear RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_GENERIC_NOTIFY_STATE_CLEAR_ENTER](*1e6).3f us\n"

// MSG3_RTOS_GENERIC_NOTIFY_VALUE_CLEAR_ENTER ""
#define MSG3_RTOS_GENERIC_NOTIFY_VALUE_CLEAR_ENTER 1016U
// >>RTOS_MAIN "%N %t ulTaskGenericNotifyValueClear ENTER: xTask 0x%08X, uxIndexToClear %u, "
// >>RTOS_MAIN "ulBitsToClear 0x%08X\n"

// MSG1_RTOS_GENERIC_NOTIFY_VALUE_CLEAR_RETURN ""
#define MSG1_RTOS_GENERIC_NOTIFY_VALUE_CLEAR_RETURN 1024U
// >>RTOS_MAIN "%N %t ulTaskGenericNotifyValueClear RETURN: ulReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_GENERIC_NOTIFY_VALUE_CLEAR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_RUN_TIME_COUNTER_ENTER ""
#define MSG1_RTOS_GET_RUN_TIME_COUNTER_ENTER 1026U
// >>RTOS_MAIN "%N %t ulTaskGetRunTimeCounter ENTER: xTask 0x%08X\n"

// MSG1_RTOS_GET_RUN_TIME_COUNTER_RETURN ""
#define MSG1_RTOS_GET_RUN_TIME_COUNTER_RETURN 1028U
// >>RTOS_MAIN "%N %t ulTaskGetRunTimeCounter RETURN: ulRunTimeCounter %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_RUN_TIME_COUNTER_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_RUN_TIME_PERCENT_ENTER ""
#define MSG1_RTOS_GET_RUN_TIME_PERCENT_ENTER 1030U
// >>RTOS_MAIN "%N %t ulTaskGetRunTimePercent ENTER: xTask 0x%08X\n"

// MSG1_RTOS_GET_RUN_TIME_PERCENT_RETURN ""
#define MSG1_RTOS_GET_RUN_TIME_PERCENT_RETURN 1032U
// >>RTOS_MAIN "%N %t ulTaskGetRunTimePercent RETURN: ulReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_RUN_TIME_PERCENT_ENTER](*1e6).3f us\n"

// MSG0_RTOS_GET_IDLE_RUN_TIME_COUNTER_ENTER ""
#define MSG0_RTOS_GET_IDLE_RUN_TIME_COUNTER_ENTER 1009U
// >>RTOS_MAIN "%N %t ulTaskGetIdleRunTimeCounter ENTER\n"

// MSG1_RTOS_GET_IDLE_RUN_TIME_COUNTER_RETURN ""
#define MSG1_RTOS_GET_IDLE_RUN_TIME_COUNTER_RETURN 1034U
// >>RTOS_MAIN "%N %t ulTaskGetIdleRunTimeCounter RETURN: ulReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_GET_IDLE_RUN_TIME_COUNTER_ENTER](*1e6).3f us\n"

// MSG0_RTOS_GET_IDLE_RUN_TIME_PERCENT_ENTER ""
#define MSG0_RTOS_GET_IDLE_RUN_TIME_PERCENT_ENTER 1036U
// >>RTOS_MAIN "%N %t ulTaskGetIdleRunTimePercent ENTER\n"

// MSG1_RTOS_GET_IDLE_RUN_TIME_PERCENT_RETURN ""
#define MSG1_RTOS_GET_IDLE_RUN_TIME_PERCENT_RETURN 1038U
// >>RTOS_MAIN "%N %t ulTaskGetIdleRunTimePercent RETURN: ulReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_GET_IDLE_RUN_TIME_PERCENT_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GET_MPU_SETTINGS_ENTER ""
#define MSG1_RTOS_GET_MPU_SETTINGS_ENTER 1040U
// >>RTOS_MAIN "%N %t xTaskGetMPUSettings ENTER: xTask 0x%08X\n"

// MSG1_RTOS_GET_MPU_SETTINGS_RETURN ""
#define MSG1_RTOS_GET_MPU_SETTINGS_RETURN 1042U
// >>RTOS_MAIN "%N %t xTaskGetMPUSettings RETURN: xMPUSettings 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GET_MPU_SETTINGS_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_GENERIC_RESET_ENTER ""
#define MSG2_RTOS_QUEUE_GENERIC_RESET_ENTER 1044U
// >>RTOS_MAIN "%N %t xQueueGenericReset ENTER: xQueue 0x%08X, xNewQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_GENERIC_RESET_RETURN ""
#define MSG1_RTOS_QUEUE_GENERIC_RESET_RETURN 1048U
// >>RTOS_MAIN "%N %t xQueueGenericReset RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_GENERIC_RESET_ENTER](*1e6).3f us\n"

// MSG5_RTOS_QUEUE_GENERIC_CREATE_STATIC_ENTER ""
#define MSG5_RTOS_QUEUE_GENERIC_CREATE_STATIC_ENTER 1056U
// >>RTOS_MAIN "%N %t xQueueGenericCreateStatic ENTER: uxQueueLength %u, uxItemSize %u, "
// >>RTOS_MAIN "pucQueueStorage 0x%08X, pxStaticQueue 0x%08X, ucQueueType %u\n"

// MSG1_RTOS_QUEUE_GENERIC_CREATE_STATIC_RETURN ""
#define MSG1_RTOS_QUEUE_GENERIC_CREATE_STATIC_RETURN 1050U
// >>RTOS_MAIN "%N %t xQueueGenericCreateStatic RETURN: pxNewQueue 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG5_RTOS_QUEUE_GENERIC_CREATE_STATIC_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_GENERIC_GET_STATIC_BUFFERS_ENTER ""
#define MSG3_RTOS_QUEUE_GENERIC_GET_STATIC_BUFFERS_ENTER 1072U
// >>RTOS_MAIN "%N %t xQueueGenericGetStaticBuffers ENTER: xQueue 0x%08X, ppucQueueStorage 0x%08X, "
// >>RTOS_MAIN "ppxStaticQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_GENERIC_GET_STATIC_BUFFERS_RETURN ""
#define MSG1_RTOS_QUEUE_GENERIC_GET_STATIC_BUFFERS_RETURN 1052U
// >>RTOS_MAIN "%N %t xQueueGenericGetStaticBuffers RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_GENERIC_GET_STATIC_BUFFERS_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_GENERIC_CREATE_ENTER ""
#define MSG3_RTOS_QUEUE_GENERIC_CREATE_ENTER 1080U
// >>RTOS_MAIN "%N %t xQueueGenericCreate ENTER: uxQueueLength %u, uxItemSize %u, ucQueueType %u\n"

// MSG1_RTOS_QUEUE_GENERIC_CREATE_RETURN ""
#define MSG1_RTOS_QUEUE_GENERIC_CREATE_RETURN 1054U
// >>RTOS_MAIN "%N %t xQueueGenericCreate RETURN: pxNewQueue 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_GENERIC_CREATE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_CREATE_MUTEX_ENTER ""
#define MSG1_RTOS_QUEUE_CREATE_MUTEX_ENTER 1088U
// >>RTOS_MAIN "%N %t xQueueCreateMutex ENTER: ucQueueType %u\n"

// MSG1_RTOS_QUEUE_CREATE_MUTEX_RETURN ""
#define MSG1_RTOS_QUEUE_CREATE_MUTEX_RETURN 1090U
// >>RTOS_MAIN "%N %t xQueueCreateMutex RETURN: xNewQueue 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_CREATE_MUTEX_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_CREATE_MUTEX_STATIC_ENTER ""
#define MSG2_RTOS_QUEUE_CREATE_MUTEX_STATIC_ENTER 1092U
// >>RTOS_MAIN "%N %t xQueueCreateMutexStatic ENTER: ucQueueType %u, pxStaticQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_CREATE_MUTEX_STATIC_RETURN ""
#define MSG1_RTOS_QUEUE_CREATE_MUTEX_STATIC_RETURN 1096U
// >>RTOS_MAIN "%N %t xQueueCreateMutexStatic RETURN: xNewQueue 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_CREATE_MUTEX_STATIC_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_ENTER ""
#define MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_ENTER 1098U
// >>RTOS_MAIN "%N %t xQueueGetMutexHolder ENTER: xSemaphore 0x%08X\n"

// MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_RETURN ""
#define MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_RETURN 1100U
// >>RTOS_MAIN "%N %t xQueueGetMutexHolder RETURN: pxReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_FROM_ISR_ENTER ""
#define MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_FROM_ISR_ENTER 1102U
// >>RTOS_MAIN "%N %t xQueueGetMutexHolderFromISR ENTER: xSemaphore 0x%08X\n"

// MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_FROM_ISR_RETURN 1104U
// >>RTOS_MAIN "%N %t xQueueGetMutexHolderFromISR RETURN: pxReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_GET_MUTEX_HOLDER_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_GIVE_MUTEX_RECURSIVE_ENTER ""
#define MSG1_RTOS_GIVE_MUTEX_RECURSIVE_ENTER 1106U
// >>RTOS_MAIN "%N %t xQueueGiveMutexRecursive ENTER: xMutex 0x%08X\n"

// MSG1_RTOS_GIVE_MUTEX_RECURSIVE_RETURN ""
#define MSG1_RTOS_GIVE_MUTEX_RECURSIVE_RETURN 1108U
// >>RTOS_MAIN "%N %t xQueueGiveMutexRecursive RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_GIVE_MUTEX_RECURSIVE_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TAKE_MUTEX_RECURSIVE_ENTER ""
#define MSG2_RTOS_TAKE_MUTEX_RECURSIVE_ENTER 1112U
// >>RTOS_MAIN "%N %t xQueueTakeMutexRecursive ENTER: xMutex 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_TAKE_MUTEX_RECURSIVE_RETURN ""
#define MSG1_RTOS_TAKE_MUTEX_RECURSIVE_RETURN 1110U
// >>RTOS_MAIN "%N %t xQueueTakeMutexRecursive RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TAKE_MUTEX_RECURSIVE_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_STATIC_ENTER ""
#define MSG3_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_STATIC_ENTER 1120U
// >>RTOS_MAIN "%N %t xQueueCreateCountingSemaphoreStatic ENTER: uxMaxCount %u, "
// >>RTOS_MAIN "uxInitialCount %u, pxStaticQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_STATIC_RETURN ""
#define MSG1_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_STATIC_RETURN 1116U
// >>RTOS_MAIN "%N %t xQueueCreateCountingSemaphoreStatic RETURN: xHandle 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_STATIC_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_ENTER ""
#define MSG2_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_ENTER 1128U
// >>RTOS_MAIN "%N %t xQueueCreateCountingSemaphore ENTER: uxMaxCount %u, uxInitialCount %u\n"

// MSG1_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_RETURN ""
#define MSG1_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_RETURN 1118U
// >>RTOS_MAIN "%N %t xQueueCreateCountingSemaphore RETURN: xHandle 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_CREATE_COUNTING_SEMAPHORE_ENTER](*1e6).3f us\n"

// MSG4_RTOS_QUEUE_GENERIC_SEND_ENTER ""
#define MSG4_RTOS_QUEUE_GENERIC_SEND_ENTER 1136U
// >>RTOS_MAIN "%N %t xQueueGenericSend ENTER: xQueue 0x%08X, pvItemToQueue 0x%08X, "
// >>RTOS_MAIN "xTicksToWait %u, xCopyPosition %u\n"

// MSG1_RTOS_QUEUE_GENERIC_SEND_RETURN ""
#define MSG1_RTOS_QUEUE_GENERIC_SEND_RETURN 1132U
// >>RTOS_MAIN "%N %t xQueueGenericSend RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_QUEUE_GENERIC_SEND_ENTER](*1e6).3f us\n"

// MSG4_RTOS_QUEUE_GENERIC_SEND_FROM_ISR_ENTER ""
#define MSG4_RTOS_QUEUE_GENERIC_SEND_FROM_ISR_ENTER 1152U
// >>RTOS_MAIN "%N %t xQueueGenericSendFromISR ENTER: xQueue 0x%08X, pvItemToQueue 0x%08X, "
// >>RTOS_MAIN "pxHigherPriorityTaskWoken 0x%08X, xCopyPosition %u\n"

// MSG1_RTOS_QUEUE_GENERIC_SEND_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_GENERIC_SEND_FROM_ISR_RETURN 1134U
// >>RTOS_MAIN "%N %t xQueueGenericSendFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_QUEUE_GENERIC_SEND_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_GIVE_FROM_ISR_ENTER ""
#define MSG2_RTOS_QUEUE_GIVE_FROM_ISR_ENTER 1168U
// >>RTOS_MAIN "%N %t xQueueGiveFromISR ENTER: xQueue 0x%08X, pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_QUEUE_GIVE_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_GIVE_FROM_ISR_RETURN 1172U
// >>RTOS_MAIN "%N %t xQueueGiveFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_GIVE_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_RECEIVE_ENTER ""
#define MSG3_RTOS_QUEUE_RECEIVE_ENTER 1176U
// >>RTOS_MAIN "%N %t xQueueReceive ENTER: xQueue 0x%08X, pvBuffer 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_QUEUE_RECEIVE_RETURN ""
#define MSG1_RTOS_QUEUE_RECEIVE_RETURN 1174U
// >>RTOS_MAIN "%N %t xQueueReceive RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_RECEIVE_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_SEMAPHORE_TAKE_ENTER ""
#define MSG2_RTOS_QUEUE_SEMAPHORE_TAKE_ENTER 1184U
// >>RTOS_MAIN "%N %t xQueueSemaphoreTake ENTER: xQueue 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_QUEUE_SEMAPHORE_TAKE_RETURN ""
#define MSG1_RTOS_QUEUE_SEMAPHORE_TAKE_RETURN 1188U
// >>RTOS_MAIN "%N %t xQueueSemaphoreTake RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_SEMAPHORE_TAKE_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_PEEK_ENTER ""
#define MSG3_RTOS_QUEUE_PEEK_ENTER 1192U
// >>RTOS_MAIN "%N %t xQueuePeek ENTER: xQueue 0x%08X, pvBuffer 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_QUEUE_PEEK_RETURN ""
#define MSG1_RTOS_QUEUE_PEEK_RETURN 1190U
// >>RTOS_MAIN "%N %t xQueuePeek RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_PEEK_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_RECEIVE_FROM_ISR_ENTER ""
#define MSG3_RTOS_QUEUE_RECEIVE_FROM_ISR_ENTER 1200U
// >>RTOS_MAIN "%N %t xQueueReceiveFromISR ENTER: xQueue 0x%08X, pvBuffer 0x%08X, "
// >>RTOS_MAIN "pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_QUEUE_RECEIVE_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_RECEIVE_FROM_ISR_RETURN 1208U
// >>RTOS_MAIN "%N %t xQueueReceiveFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_RECEIVE_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_PEEK_FROM_ISR_ENTER ""
#define MSG2_RTOS_QUEUE_PEEK_FROM_ISR_ENTER 1212U
// >>RTOS_MAIN "%N %t xQueuePeekFromISR ENTER: xQueue 0x%08X, pvBuffer 0x%08X\n"

// MSG1_RTOS_QUEUE_PEEK_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_PEEK_FROM_ISR_RETURN 1210U
// >>RTOS_MAIN "%N %t xQueuePeekFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_PEEK_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_MESSAGES_WAITING_ENTER ""
#define MSG1_RTOS_QUEUE_MESSAGES_WAITING_ENTER 1216U
// >>RTOS_MAIN "%N %t uxQueueMessagesWaiting ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_MESSAGES_WAITING_RETURN ""
#define MSG1_RTOS_QUEUE_MESSAGES_WAITING_RETURN 1218U
// >>RTOS_MAIN "%N %t uxQueueMessagesWaiting RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_MESSAGES_WAITING_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_SPACES_AVAILABLE_ENTER ""
#define MSG1_RTOS_QUEUE_SPACES_AVAILABLE_ENTER 1220U
// >>RTOS_MAIN "%N %t uxQueueSpacesAvailable ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_SPACES_AVAILABLE_RETURN ""
#define MSG1_RTOS_QUEUE_SPACES_AVAILABLE_RETURN 1222U
// >>RTOS_MAIN "%N %t uxQueueSpacesAvailable RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_SPACES_AVAILABLE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_MESSAGES_WAITING_FROM_ISR_ENTER ""
#define MSG1_RTOS_QUEUE_MESSAGES_WAITING_FROM_ISR_ENTER 1224U
// >>RTOS_MAIN "%N %t uxQueueMessagesWaitingFromISR ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_MESSAGES_WAITING_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_MESSAGES_WAITING_FROM_ISR_RETURN 1226U
// >>RTOS_MAIN "%N %t uxQueueMessagesWaitingFromISR RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_MESSAGES_WAITING_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_DELETE_ENTER ""
#define MSG1_RTOS_QUEUE_DELETE_ENTER 1228U
// >>RTOS_MAIN "%N %t vQueueDelete ENTER: xQueue 0x%08X\n"

// MSG0_RTOS_QUEUE_DELETE_RETURN ""
#define MSG0_RTOS_QUEUE_DELETE_RETURN 1037U
// >>RTOS_MAIN "%N %t vQueueDelete RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_DELETE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_GET_QUEUE_NUMBER_ENTER ""
#define MSG1_RTOS_QUEUE_GET_QUEUE_NUMBER_ENTER 1230U
// >>RTOS_MAIN "%N %t uxQueueGetQueueNumber ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_GET_QUEUE_NUMBER_RETURN ""
#define MSG1_RTOS_QUEUE_GET_QUEUE_NUMBER_RETURN 1232U
// >>RTOS_MAIN "%N %t uxQueueGetQueueNumber RETURN: uxQueueNumber %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_GET_QUEUE_NUMBER_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_SET_QUEUE_NUMBER_ENTER ""
#define MSG2_RTOS_QUEUE_SET_QUEUE_NUMBER_ENTER 1236U
// >>RTOS_MAIN "%N %t vQueueSetQueueNumber ENTER: xQueue 0x%08X, uxQueueNumber %u\n"

// MSG0_RTOS_QUEUE_SET_QUEUE_NUMBER_RETURN ""
#define MSG0_RTOS_QUEUE_SET_QUEUE_NUMBER_RETURN 1234U
// >>RTOS_MAIN "%N %t vQueueSetQueueNumber RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_SET_QUEUE_NUMBER_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_GET_QUEUE_TYPE_ENTER ""
#define MSG1_RTOS_QUEUE_GET_QUEUE_TYPE_ENTER 1240U
// >>RTOS_MAIN "%N %t ucQueueGetQueueType ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_GET_QUEUE_TYPE_RETURN ""
#define MSG1_RTOS_QUEUE_GET_QUEUE_TYPE_RETURN 1242U
// >>RTOS_MAIN "%N %t ucQueueGetQueueType RETURN: ucQueueType %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_GET_QUEUE_TYPE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_GET_QUEUE_ITEM_SIZE_ENTER ""
#define MSG1_RTOS_QUEUE_GET_QUEUE_ITEM_SIZE_ENTER 1244U
// >>RTOS_MAIN "%N %t uxQueueGetQueueItemSize ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_GET_QUEUE_ITEM_SIZE_RETURN ""
#define MSG1_RTOS_QUEUE_GET_QUEUE_ITEM_SIZE_RETURN 1246U
// >>RTOS_MAIN "%N %t uxQueueGetQueueItemSize RETURN: uxItemSize %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_GET_QUEUE_ITEM_SIZE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_GET_QUEUE_LENGTH_ENTER ""
#define MSG1_RTOS_QUEUE_GET_QUEUE_LENGTH_ENTER 1248U
// >>RTOS_MAIN "%N %t uxQueueGetQueueLength ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_GET_QUEUE_LENGTH_RETURN ""
#define MSG1_RTOS_QUEUE_GET_QUEUE_LENGTH_RETURN 1250U
// >>RTOS_MAIN "%N %t uxQueueGetQueueLength RETURN: uxLength %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_GET_QUEUE_LENGTH_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_IS_EMPTY_FROM_ISR_ENTER ""
#define MSG1_RTOS_QUEUE_IS_EMPTY_FROM_ISR_ENTER 1252U
// >>RTOS_MAIN "%N %t xQueueIsQueueEmptyFromISR ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_IS_EMPTY_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_IS_EMPTY_FROM_ISR_RETURN 1254U
// >>RTOS_MAIN "%N %t xQueueIsQueueEmptyFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_IS_EMPTY_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_IS_FULL_FROM_ISR_ENTER ""
#define MSG1_RTOS_QUEUE_IS_FULL_FROM_ISR_ENTER 1256U
// >>RTOS_MAIN "%N %t xQueueIsQueueFullFromISR ENTER: xQueue 0x%08X\n"

// MSG1_RTOS_QUEUE_IS_FULL_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_IS_FULL_FROM_ISR_RETURN 1258U
// >>RTOS_MAIN "%N %t xQueueIsQueueFullFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_IS_FULL_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_CR_SEND_ENTER ""
#define MSG3_RTOS_QUEUE_CR_SEND_ENTER 1264U
// >>RTOS_MAIN "%N %t xQueueCRSend ENTER: xQueue 0x%08X, pvItemToQueue 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_QUEUE_CR_SEND_RETURN ""
#define MSG1_RTOS_QUEUE_CR_SEND_RETURN 1260U
// >>RTOS_MAIN "%N %t xQueueCRSend RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_CR_SEND_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_CR_RECEIVE_ENTER ""
#define MSG3_RTOS_QUEUE_CR_RECEIVE_ENTER 1272U
// >>RTOS_MAIN "%N %t xQueueCRReceive ENTER: xQueue 0x%08X, pvBuffer 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_QUEUE_CR_RECEIVE_RETURN ""
#define MSG1_RTOS_QUEUE_CR_RECEIVE_RETURN 1262U
// >>RTOS_MAIN "%N %t xQueueCRReceive RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_CR_RECEIVE_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_CR_SEND_FROM_ISR_ENTER ""
#define MSG3_RTOS_QUEUE_CR_SEND_FROM_ISR_ENTER 1280U
// >>RTOS_MAIN "%N %t xQueueCRSendFromISR ENTER: xQueue 0x%08X, pvItemToQueue 0x%08X, "
// >>RTOS_MAIN "xCoRoutinePreviouslyWoken 0x%08X\n"

// MSG1_RTOS_QUEUE_CR_SEND_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_CR_SEND_FROM_ISR_RETURN 1288U
// >>RTOS_MAIN "%N %t xQueueCRSendFromISR RETURN: xCoRoutinePreviouslyWoken 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_CR_SEND_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_CR_RECEIVE_FROM_ISR_ENTER ""
#define MSG3_RTOS_QUEUE_CR_RECEIVE_FROM_ISR_ENTER 1296U
// >>RTOS_MAIN "%N %t xQueueCRReceiveFromISR ENTER: xQueue 0x%08X, pvBuffer 0x%08X, "
// >>RTOS_MAIN "pxCoRoutineWoken 0x%08X\n"

// MSG1_RTOS_QUEUE_CR_RECEIVE_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_CR_RECEIVE_FROM_ISR_RETURN 1290U
// >>RTOS_MAIN "%N %t xQueueCRReceiveFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_CR_RECEIVE_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_ADD_TO_REGISTRY_ENTER ""
#define MSG2_RTOS_QUEUE_ADD_TO_REGISTRY_ENTER 1292U
// >>RTOS_MAIN "%N %t vQueueAddToRegistry ENTER: xQueue 0x%08X, pcQueueName 0x%08X\n"

// MSG0_RTOS_QUEUE_ADD_TO_REGISTRY_RETURN ""
#define MSG0_RTOS_QUEUE_ADD_TO_REGISTRY_RETURN 1235U
// >>RTOS_MAIN "%N %t vQueueAddToRegistry RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_ADD_TO_REGISTRY_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_GET_NAME_ENTER ""
#define MSG1_RTOS_QUEUE_GET_NAME_ENTER 1304U
// >>RTOS_MAIN "%N %t pcQueueGetName ENTER - 0x%08X\n"

// MSG1_RTOS_QUEUE_GET_NAME_RETURN ""
#define MSG1_RTOS_QUEUE_GET_NAME_RETURN 1306U
// >>RTOS_MAIN "%N %t pcQueueGetName RETURN: pcReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_GET_NAME_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_UNREGISTER_ENTER ""
#define MSG1_RTOS_QUEUE_UNREGISTER_ENTER 1308U
// >>RTOS_MAIN "%N %t vQueueUnregisterQueue ENTER: xQueue 0x%08X\n"

// MSG0_RTOS_QUEUE_UNREGISTER_RETURN ""
#define MSG0_RTOS_QUEUE_UNREGISTER_RETURN 1310U
// >>RTOS_MAIN "%N %t vQueueUnregisterQueue RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_UNREGISTER_ENTER](*1e6).3f us\n"

// MSG3_RTOS_QUEUE_WAIT_FOR_MESSAGE_RESTRICTED_ENTER ""
#define MSG3_RTOS_QUEUE_WAIT_FOR_MESSAGE_RESTRICTED_ENTER 1312U
// >>RTOS_MAIN "%N %t vQueueWaitForMessageRestricted ENTER: xQueue 0x%08X, "
// >>RTOS_MAIN "xTicksToWait %u, xWaitIndefinitely %u\n"

// MSG0_RTOS_QUEUE_WAIT_FOR_MESSAGE_RESTRICTED_RETURN ""
#define MSG0_RTOS_QUEUE_WAIT_FOR_MESSAGE_RESTRICTED_RETURN 1311U
// >>RTOS_MAIN "%N %t vQueueWaitForMessageRestricted RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_QUEUE_WAIT_FOR_MESSAGE_RESTRICTED_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_CREATE_SET_ENTER ""
#define MSG1_RTOS_QUEUE_CREATE_SET_ENTER 1320U
// >>RTOS_MAIN "%N %t xQueueCreateSet ENTER: uxEventQueueLength %u\n"

// MSG1_RTOS_QUEUE_CREATE_SET_RETURN ""
#define MSG1_RTOS_QUEUE_CREATE_SET_RETURN 1322U
// >>RTOS_MAIN "%N %t xQueueCreateSet RETURN: pxQueue 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_CREATE_SET_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_CREATE_SET_STATIC_ENTER ""
#define MSG1_RTOS_QUEUE_CREATE_SET_STATIC_ENTER 1324U
// >>RTOS_MAIN "%N %t xQueueCreateSetStatic ENTER: uxEventQueueLength %u\n"

// MSG1_RTOS_QUEUE_CREATE_SET_STATIC_RETURN ""
#define MSG1_RTOS_QUEUE_CREATE_SET_STATIC_RETURN 1326U
// >>RTOS_MAIN "%N %t xQueueCreateSetStatic RETURN: pxQueue 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_CREATE_SET_STATIC_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_ADD_TO_SET_ENTER ""
#define MSG2_RTOS_QUEUE_ADD_TO_SET_ENTER 1328U
// >>RTOS_MAIN "%N %t xQueueAddToSet ENTER: xQueueOrSemaphore 0x%08X, xQueueSet 0x%08X\n"

// MSG1_RTOS_QUEUE_ADD_TO_SET_RETURN ""
#define MSG1_RTOS_QUEUE_ADD_TO_SET_RETURN 1332U
// >>RTOS_MAIN "%N %t xQueueAddToSet RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_ADD_TO_SET_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_REMOVE_FROM_SET_ENTER ""
#define MSG2_RTOS_QUEUE_REMOVE_FROM_SET_ENTER 1336U
// >>RTOS_MAIN "%N %t xQueueRemoveFromSet ENTER: xQueueOrSemaphore 0x%08X, xQueueSet 0x%08X\n"

// MSG1_RTOS_QUEUE_REMOVE_FROM_SET_RETURN ""
#define MSG1_RTOS_QUEUE_REMOVE_FROM_SET_RETURN 1334U
// >>RTOS_MAIN "%N %t xQueueRemoveFromSet RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_REMOVE_FROM_SET_ENTER](*1e6).3f us\n"

// MSG2_RTOS_QUEUE_SELECT_FROM_SET_ENTER ""
#define MSG2_RTOS_QUEUE_SELECT_FROM_SET_ENTER 1340U
// >>RTOS_MAIN "%N %t xQueueSelectFromSet ENTER: xQueueSet 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_QUEUE_SELECT_FROM_SET_RETURN ""
#define MSG1_RTOS_QUEUE_SELECT_FROM_SET_RETURN 1344U
// >>RTOS_MAIN "%N %t xQueueSelectFromSet RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_QUEUE_SELECT_FROM_SET_ENTER](*1e6).3f us\n"

// MSG1_RTOS_QUEUE_SELECT_FROM_SET_FROM_ISR_ENTER ""
#define MSG1_RTOS_QUEUE_SELECT_FROM_SET_FROM_ISR_ENTER 1346U
// >>RTOS_MAIN "%N %t xQueueSelectFromSetFromISR ENTER: xQueueSet 0x%08X\n"

// MSG1_RTOS_QUEUE_SELECT_FROM_SET_FROM_ISR_RETURN ""
#define MSG1_RTOS_QUEUE_SELECT_FROM_SET_FROM_ISR_RETURN 1348U
// >>RTOS_MAIN "%N %t xQueueSelectFromSetFromISR RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_QUEUE_SELECT_FROM_SET_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG0_RTOS_TIMER_CREATE_TIMER_TASK_ENTER ""
#define MSG0_RTOS_TIMER_CREATE_TIMER_TASK_ENTER 1350U
// >>RTOS_MAIN "%N %t xTimerCreateTimerTask ENTER\n"

// MSG1_RTOS_TIMER_CREATE_TIMER_TASK_RETURN ""
#define MSG1_RTOS_TIMER_CREATE_TIMER_TASK_RETURN 1352U
// >>RTOS_MAIN "%N %t xTimerCreateTimerTask RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_TIMER_CREATE_TIMER_TASK_ENTER](*1e6).3f us\n"

// MSG5_RTOS_TIMER_CREATE_ENTER ""
#define MSG5_RTOS_TIMER_CREATE_ENTER 1360U
// >>RTOS_MAIN "%N %t xTimerCreate ENTER: pcTimerName 0x%08X, xTimerPeriodInTicks %u, xAutoReload %u, "
// >>RTOS_MAIN "pvTimerID 0x%08X, pxCallbackFunction 0x%08X\n"

// MSG1_RTOS_TIMER_CREATE_RETURN ""
#define MSG1_RTOS_TIMER_CREATE_RETURN 1354U
// >>RTOS_MAIN "%N %t xTimerCreate RETURN: pxNewTimer 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG5_RTOS_TIMER_CREATE_ENTER](*1e6).3f us\n"

// MSG6_RTOS_TIMER_CREATE_STATIC_ENTER ""
#define MSG6_RTOS_TIMER_CREATE_STATIC_ENTER 1376U
// >>RTOS_MAIN "%N %t xTimerCreateStatic ENTER: pcTimerName 0x%08X, xTimerPeriodInTicks %u, xAutoReload %u, "
// >>RTOS_MAIN "pvTimerID 0x%08X, pxCallbackFunction 0x%08X, pxTimerBuffer 0x%08X\n"

// MSG1_RTOS_TIMER_CREATE_STATIC_RETURN ""
#define MSG1_RTOS_TIMER_CREATE_STATIC_RETURN 1356U
// >>RTOS_MAIN "%N %t xTimerCreateStatic RETURN: pxNewTimer 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG6_RTOS_TIMER_CREATE_STATIC_ENTER](*1e6).3f us\n"

// MSG5_RTOS_TIMER_GENERIC_COMMAND_FROM_TASK_ENTER ""
#define MSG5_RTOS_TIMER_GENERIC_COMMAND_FROM_TASK_ENTER 1392U
// >>RTOS_MAIN "%N %t xTimerGenericCommandFromTask ENTER: xTimer 0x%08X, xCommandID %u, "
// >>RTOS_MAIN "xOptionalValue %u, pxHigherPriorityTaskWoken 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_TIMER_GENERIC_COMMAND_FROM_TASK_RETURN ""
#define MSG1_RTOS_TIMER_GENERIC_COMMAND_FROM_TASK_RETURN 1358U
// >>RTOS_MAIN "%N %t xTimerGenericCommandFromTask RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG5_RTOS_TIMER_GENERIC_COMMAND_FROM_TASK_ENTER](*1e6).3f us\n"

// MSG5_RTOS_TIMER_GENERIC_COMMAND_FROM_ISR_ENTER ""
#define MSG5_RTOS_TIMER_GENERIC_COMMAND_FROM_ISR_ENTER 1408U
// >>RTOS_MAIN "%N %t xTimerGenericCommandFromISR ENTER: xTimer 0x%08X, xCommandID %u, "
// >>RTOS_MAIN "xOptionalValue %u, pxHigherPriorityTaskWoken 0x%08X, xTicksToWait %u\n"

// MSG1_RTOS_TIMER_GENERIC_COMMAND_FROM_ISR_RETURN ""
#define MSG1_RTOS_TIMER_GENERIC_COMMAND_FROM_ISR_RETURN 1424U
// >>RTOS_MAIN "%N %t xTimerGenericCommandFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG5_RTOS_TIMER_GENERIC_COMMAND_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG0_RTOS_TIMER_GET_DAEMON_TASK_HANDLE_ENTER ""
#define MSG0_RTOS_TIMER_GET_DAEMON_TASK_HANDLE_ENTER 1351U
// >>RTOS_MAIN "%N %t xTimerGetTimerDaemonTaskHandle ENTER\n"

// MSG1_RTOS_TIMER_GET_DAEMON_TASK_HANDLE_RETURN ""
#define MSG1_RTOS_TIMER_GET_DAEMON_TASK_HANDLE_RETURN 1426U
// >>RTOS_MAIN "%N %t xTimerGetTimerDaemonTaskHandle RETURN: xTimerTaskHandle 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_TIMER_GET_DAEMON_TASK_HANDLE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TIMER_GET_PERIOD_ENTER ""
#define MSG1_RTOS_TIMER_GET_PERIOD_ENTER 1428U
// >>RTOS_MAIN "%N %t xTimerGetPeriod ENTER: xTimer 0x%08X\n"

// MSG1_RTOS_TIMER_GET_PERIOD_RETURN ""
#define MSG1_RTOS_TIMER_GET_PERIOD_RETURN 1430U
// >>RTOS_MAIN "%N %t xTimerGetPeriod RETURN: xTimerPeriodInTicks %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TIMER_GET_PERIOD_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TIMER_SET_RELOAD_MODE_ENTER ""
#define MSG2_RTOS_TIMER_SET_RELOAD_MODE_ENTER 1432U
// >>RTOS_MAIN "%N %t vTimerSetReloadMode ENTER: xTimer 0x%08X, xAutoReload %u\n"

// MSG0_RTOS_TIMER_SET_RELOAD_MODE_RETURN ""
#define MSG0_RTOS_TIMER_SET_RELOAD_MODE_RETURN 1436U
// >>RTOS_MAIN "%N %t vTimerSetReloadMode RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TIMER_SET_RELOAD_MODE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TIMER_GET_RELOAD_MODE_ENTER ""
#define MSG1_RTOS_TIMER_GET_RELOAD_MODE_ENTER 1438U
// >>RTOS_MAIN "%N %t xTimerGetReloadMode ENTER: xTimer 0x%08X\n"

// MSG1_RTOS_TIMER_GET_RELOAD_MODE_RETURN ""
#define MSG1_RTOS_TIMER_GET_RELOAD_MODE_RETURN 1440U
// >>RTOS_MAIN "%N %t xTimerGetReloadMode RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TIMER_GET_RELOAD_MODE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TIMER_UX_GET_RELOAD_MODE_ENTER ""
#define MSG1_RTOS_TIMER_UX_GET_RELOAD_MODE_ENTER 1442U
// >>RTOS_MAIN "%N %t uxTimerGetReloadMode ENTER: xTimer 0x%08X\n"

// MSG1_RTOS_TIMER_UX_GET_RELOAD_MODE_RETURN ""
#define MSG1_RTOS_TIMER_UX_GET_RELOAD_MODE_RETURN 1444U
// >>RTOS_MAIN "%N %t uxTimerGetReloadMode RETURN: uxReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TIMER_UX_GET_RELOAD_MODE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TIMER_GET_EXPIRY_TIME_ENTER ""
#define MSG1_RTOS_TIMER_GET_EXPIRY_TIME_ENTER 1446U
// >>RTOS_MAIN "%N %t xTimerGetExpiryTime ENTER: xTimer 0x%08X\n"

// MSG1_RTOS_TIMER_GET_EXPIRY_TIME_RETURN ""
#define MSG1_RTOS_TIMER_GET_EXPIRY_TIME_RETURN 1448U
// >>RTOS_MAIN "%N %t xTimerGetExpiryTime RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TIMER_GET_EXPIRY_TIME_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TIMER_GET_STATIC_BUFFER_ENTER ""
#define MSG2_RTOS_TIMER_GET_STATIC_BUFFER_ENTER 1452U
// >>RTOS_MAIN "%N %t xTimerGetStaticBuffer ENTER: xTimer 0x%08X, ppxTimerBuffer 0x%08X\n"

// MSG1_RTOS_TIMER_GET_STATIC_BUFFER_RETURN ""
#define MSG1_RTOS_TIMER_GET_STATIC_BUFFER_RETURN 1450U
// >>RTOS_MAIN "%N %t xTimerGetStaticBuffer RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TIMER_GET_STATIC_BUFFER_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TIMER_GET_NAME_ENTER ""
#define MSG1_RTOS_TIMER_GET_NAME_ENTER 1456U
// >>RTOS_MAIN "%N %t pcTimerGetName ENTER: xTimer 0x%08X\n"

// MSG1_RTOS_TIMER_GET_NAME_RETURN ""
#define MSG1_RTOS_TIMER_GET_NAME_RETURN 1458U
// >>RTOS_MAIN "%N %t pcTimerGetName RETURN: pcTimerName 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TIMER_GET_NAME_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TIMER_IS_ACTIVE_ENTER ""
#define MSG1_RTOS_TIMER_IS_ACTIVE_ENTER 1460U
// >>RTOS_MAIN "%N %t xTimerIsTimerActive ENTER: xTimer 0x%08X\n"

// MSG1_RTOS_TIMER_IS_ACTIVE_RETURN ""
#define MSG1_RTOS_TIMER_IS_ACTIVE_RETURN 1462U
// >>RTOS_MAIN "%N %t xTimerIsTimerActive RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TIMER_IS_ACTIVE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TIMER_GET_TIMER_ID_ENTER ""
#define MSG1_RTOS_TIMER_GET_TIMER_ID_ENTER 1464U
// >>RTOS_MAIN "%N %t pvTimerGetTimerID ENTER: xTimer 0x%08X\n"

// MSG1_RTOS_TIMER_GET_TIMER_ID_RETURN ""
#define MSG1_RTOS_TIMER_GET_TIMER_ID_RETURN 1466U
// >>RTOS_MAIN "%N %t pvTimerGetTimerID RETURN: pvReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TIMER_GET_TIMER_ID_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TIMER_SET_TIMER_ID_ENTER ""
#define MSG2_RTOS_TIMER_SET_TIMER_ID_ENTER 1468U
// >>RTOS_MAIN "%N %t vTimerSetTimerID ENTER: xTimer 0x%08X, pvNewID 0x%08X\n"

// MSG0_RTOS_TIMER_SET_TIMER_ID_RETURN ""
#define MSG0_RTOS_TIMER_SET_TIMER_ID_RETURN 1437U
// >>RTOS_MAIN "%N %t vTimerSetTimerID RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TIMER_SET_TIMER_ID_ENTER](*1e6).3f us\n"

// MSG4_RTOS_TIMER_PEND_FUNCTION_CALL_FROM_ISR_ENTER ""
#define MSG4_RTOS_TIMER_PEND_FUNCTION_CALL_FROM_ISR_ENTER 1472U
// >>RTOS_MAIN "%N %t xTimerPendFunctionCallFromISR ENTER: xFunctionToPend 0x%08X, "
// >>RTOS_MAIN "pvParameter1 0x%08X, ulParameter2 %u, pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_TIMER_PEND_FUNCTION_CALL_FROM_ISR_RETURN ""
#define MSG1_RTOS_TIMER_PEND_FUNCTION_CALL_FROM_ISR_RETURN 1488U
// >>RTOS_MAIN "%N %t xTimerPendFunctionCallFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_TIMER_PEND_FUNCTION_CALL_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG4_RTOS_TIMER_PEND_FUNCTION_CALL_ENTER ""
#define MSG4_RTOS_TIMER_PEND_FUNCTION_CALL_ENTER 1504U
// >>RTOS_MAIN "%N %t xTimerPendFunctionCall ENTER: xFunctionToPend 0x%08X, pvParameter1 0x%08X, "
// >>RTOS_MAIN "ulParameter2 %u, xTicksToWait %u\n"

// MSG1_RTOS_TIMER_PEND_FUNCTION_CALL_RETURN ""
#define MSG1_RTOS_TIMER_PEND_FUNCTION_CALL_RETURN 1490U
// >>RTOS_MAIN "%N %t xTimerPendFunctionCall RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_TIMER_PEND_FUNCTION_CALL_ENTER](*1e6).3f us\n"

// MSG1_RTOS_TIMER_GET_TIMER_NUMBER_ENTER ""
#define MSG1_RTOS_TIMER_GET_TIMER_NUMBER_ENTER 1492U
// >>RTOS_MAIN "%N %t uxTimerGetTimerNumber ENTER: xTimer 0x%08X\n"

// MSG1_RTOS_TIMER_GET_TIMER_NUMBER_RETURN ""
#define MSG1_RTOS_TIMER_GET_TIMER_NUMBER_RETURN 1494U
// >>RTOS_MAIN "%N %t uxTimerGetTimerNumber RETURN: uxTimerNumber %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_TIMER_GET_TIMER_NUMBER_ENTER](*1e6).3f us\n"

// MSG2_RTOS_TIMER_SET_TIMER_NUMBER_ENTER ""
#define MSG2_RTOS_TIMER_SET_TIMER_NUMBER_ENTER 1496U
// >>RTOS_MAIN "%N %t vTimerSetTimerNumber ENTER: xTimer 0x%08X, uxTimerNumber %u\n"

// MSG0_RTOS_TIMER_SET_TIMER_NUMBER_RETURN ""
#define MSG0_RTOS_TIMER_SET_TIMER_NUMBER_RETURN 1500U
// >>RTOS_MAIN "%N %t vTimerSetTimerNumber RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_TIMER_SET_TIMER_NUMBER_ENTER](*1e6).3f us\n"

// MSG5_RTOS_STREAM_BUFFER_GENERIC_CREATE_ENTER ""
#define MSG5_RTOS_STREAM_BUFFER_GENERIC_CREATE_ENTER 1520U
// >>RTOS_MAIN "%N %t xStreamBufferGenericCreate ENTER: xBufferSizeBytes %u, xTriggerLevelBytes %u, "
// >>RTOS_MAIN "xStreamBufferType %u, pxSendCompletedCallback 0x%08X, "
// >>RTOS_MAIN "pxReceiveCompletedCallback 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_GENERIC_CREATE_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_GENERIC_CREATE_RETURN 1502U
// >>RTOS_MAIN "%N %t xStreamBufferGenericCreate RETURN: pvAllocatedMemory 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG5_RTOS_STREAM_BUFFER_GENERIC_CREATE_ENTER](*1e6).3f us\n"

// MSG7_RTOS_STREAM_BUFFER_GENERIC_CREATE_STATIC_ENTER ""
#define MSG7_RTOS_STREAM_BUFFER_GENERIC_CREATE_STATIC_ENTER 1536U
// >>RTOS_MAIN "%N %t xStreamBufferGenericCreateStatic ENTER: xBufferSizeBytes %u, xTriggerLevelBytes %u, "
// >>RTOS_MAIN "xStreamBufferType %u, pucStreamBufferStorageArea 0x%08X, pxStaticStreamBuffer 0x%08X, "
// >>RTOS_MAIN "pxSendCompletedCallback 0x%08X, pxReceiveCompletedCallback 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_GENERIC_CREATE_STATIC_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_GENERIC_CREATE_STATIC_RETURN 1552U
// >>RTOS_MAIN "%N %t xStreamBufferGenericCreateStatic RETURN: xReturn 0x%08X, "
// >>RTOS_MAIN "dt=%[t-MSG7_RTOS_STREAM_BUFFER_GENERIC_CREATE_STATIC_ENTER](*1e6).3f us\n"

// MSG3_RTOS_STREAM_BUFFER_GET_STATIC_BUFFERS_ENTER ""
#define MSG3_RTOS_STREAM_BUFFER_GET_STATIC_BUFFERS_ENTER 1560U
// >>RTOS_MAIN "%N %t xStreamBufferGetStaticBuffers ENTER: xStreamBuffer 0x%08X, "
// >>RTOS_MAIN "ppucStreamBufferStorageArea 0x%08X, ppxStaticStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_GET_STATIC_BUFFERS_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_GET_STATIC_BUFFERS_RETURN 1554U
// >>RTOS_MAIN "%N %t xStreamBufferGetStaticBuffers RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_STREAM_BUFFER_GET_STATIC_BUFFERS_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_DELETE_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_DELETE_ENTER 1556U
// >>RTOS_MAIN "%N %t vStreamBufferDelete ENTER: xStreamBuffer 0x%08X\n"

// MSG0_RTOS_STREAM_BUFFER_DELETE_RETURN ""
#define MSG0_RTOS_STREAM_BUFFER_DELETE_RETURN 1501U
// >>RTOS_MAIN "%N %t vStreamBufferDelete RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_DELETE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_RESET_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_RESET_ENTER 1558U
// >>RTOS_MAIN "%N %t xStreamBufferReset ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_RESET_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_RESET_RETURN 1568U
// >>RTOS_MAIN "%N %t xStreamBufferReset RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_RESET_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_RESET_FROM_ISR_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_RESET_FROM_ISR_ENTER 1570U
// >>RTOS_MAIN "%N %t xStreamBufferResetFromISR ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_RESET_FROM_ISR_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_RESET_FROM_ISR_RETURN 1572U
// >>RTOS_MAIN "%N %t xStreamBufferResetFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_RESET_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_STREAM_BUFFER_SET_TRIGGER_LEVEL_ENTER ""
#define MSG2_RTOS_STREAM_BUFFER_SET_TRIGGER_LEVEL_ENTER 1576U
// >>RTOS_MAIN "%N %t xStreamBufferSetTriggerLevel ENTER: xStreamBuffer 0x%08X, xTriggerLevel %u\n"

// MSG1_RTOS_STREAM_BUFFER_SET_TRIGGER_LEVEL_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_SET_TRIGGER_LEVEL_RETURN 1574U
// >>RTOS_MAIN "%N %t xStreamBufferSetTriggerLevel RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_STREAM_BUFFER_SET_TRIGGER_LEVEL_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_SPACES_AVAILABLE_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_SPACES_AVAILABLE_ENTER 1580U
// >>RTOS_MAIN "%N %t xStreamBufferSpacesAvailable ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_SPACES_AVAILABLE_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_SPACES_AVAILABLE_RETURN 1582U
// >>RTOS_MAIN "%N %t xStreamBufferSpacesAvailable RETURN: xSpace %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_SPACES_AVAILABLE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_BYTES_AVAILABLE_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_BYTES_AVAILABLE_ENTER 1584U
// >>RTOS_MAIN "%N %t xStreamBufferBytesAvailable ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_BYTES_AVAILABLE_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_BYTES_AVAILABLE_RETURN 1586U
// >>RTOS_MAIN "%N %t xStreamBufferBytesAvailable RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_BYTES_AVAILABLE_ENTER](*1e6).3f us\n"

// MSG4_RTOS_STREAM_BUFFER_SEND_ENTER ""
#define MSG4_RTOS_STREAM_BUFFER_SEND_ENTER 1600U
// >>RTOS_MAIN "%N %t xStreamBufferSend ENTER: xStreamBuffer 0x%08X, pvTxData 0x%08X, "
// >>RTOS_MAIN "xDataLengthBytes %u, xTicksToWait %u\n"

// MSG1_RTOS_STREAM_BUFFER_SEND_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_SEND_RETURN 1588U
// >>RTOS_MAIN "%N %t xStreamBufferSend RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_STREAM_BUFFER_SEND_ENTER](*1e6).3f us\n"

// MSG4_RTOS_STREAM_BUFFER_SEND_FROM_ISR_ENTER ""
#define MSG4_RTOS_STREAM_BUFFER_SEND_FROM_ISR_ENTER 1616U
// >>RTOS_MAIN "%N %t xStreamBufferSendFromISR ENTER: xStreamBuffer 0x%08X, pvTxData 0x%08X, "
// >>RTOS_MAIN "xDataLengthBytes %u, pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_SEND_FROM_ISR_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_SEND_FROM_ISR_RETURN 1590U
// >>RTOS_MAIN "%N %t xStreamBufferSendFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_STREAM_BUFFER_SEND_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG4_RTOS_STREAM_BUFFER_RECEIVE_ENTER ""
#define MSG4_RTOS_STREAM_BUFFER_RECEIVE_ENTER 1632U
// >>RTOS_MAIN "%N %t xStreamBufferReceive ENTER: xStreamBuffer 0x%08X, pvRxData 0x%08X, "
// >>RTOS_MAIN "xBufferLengthBytes %u, xTicksToWait %u\n"

// MSG1_RTOS_STREAM_BUFFER_RECEIVE_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_RECEIVE_RETURN 1592U
// >>RTOS_MAIN "%N %t xStreamBufferReceive RETURN: xReceivedLength %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_STREAM_BUFFER_RECEIVE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_NEXT_MESSAGE_LENGTH_BYTES_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_NEXT_MESSAGE_LENGTH_BYTES_ENTER 1594U
// >>RTOS_MAIN "%N %t xStreamBufferNextMessageLengthBytes ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_NEXT_MESSAGE_LENGTH_BYTES_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_NEXT_MESSAGE_LENGTH_BYTES_RETURN 1596U
// >>RTOS_MAIN "%N %t xStreamBufferNextMessageLengthBytes RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_NEXT_MESSAGE_LENGTH_BYTES_ENTER](*1e6).3f us\n"

// MSG4_RTOS_STREAM_BUFFER_RECEIVE_FROM_ISR_ENTER ""
#define MSG4_RTOS_STREAM_BUFFER_RECEIVE_FROM_ISR_ENTER 1648U
// >>RTOS_MAIN "%N %t xStreamBufferReceiveFromISR ENTER: xStreamBuffer 0x%08X, pvRxData 0x%08X, "
// >>RTOS_MAIN "xBufferLengthBytes %u, pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_RECEIVE_FROM_ISR_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_RECEIVE_FROM_ISR_RETURN 1598U
// >>RTOS_MAIN "%N %t xStreamBufferReceiveFromISR RETURN: xReceivedLength %u, "
// >>RTOS_MAIN "dt=%[t-MSG4_RTOS_STREAM_BUFFER_RECEIVE_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_IS_EMPTY_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_IS_EMPTY_ENTER 1664U
// >>RTOS_MAIN "%N %t xStreamBufferIsEmpty ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_IS_EMPTY_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_IS_EMPTY_RETURN 1666U
// >>RTOS_MAIN "%N %t xStreamBufferIsEmpty RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_IS_EMPTY_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_IS_FULL_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_IS_FULL_ENTER 1668U
// >>RTOS_MAIN "%N %t xStreamBufferIsFull ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_IS_FULL_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_IS_FULL_RETURN 1670U
// >>RTOS_MAIN "%N %t xStreamBufferIsFull RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_IS_FULL_ENTER](*1e6).3f us\n"

// MSG2_RTOS_STREAM_BUFFER_SEND_COMPLETED_FROM_ISR_ENTER ""
#define MSG2_RTOS_STREAM_BUFFER_SEND_COMPLETED_FROM_ISR_ENTER 1672U
// >>RTOS_MAIN "%N %t xStreamBufferSendCompletedFromISR ENTER: xStreamBuffer 0x%08X, "
// >>RTOS_MAIN "pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_SEND_COMPLETED_FROM_ISR_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_SEND_COMPLETED_FROM_ISR_RETURN 1676U
// >>RTOS_MAIN "%N %t xStreamBufferSendCompletedFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_STREAM_BUFFER_SEND_COMPLETED_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG2_RTOS_STREAM_BUFFER_RECEIVE_COMPLETED_FROM_ISR_ENTER ""
#define MSG2_RTOS_STREAM_BUFFER_RECEIVE_COMPLETED_FROM_ISR_ENTER 1680U
// >>RTOS_MAIN "%N %t xStreamBufferReceiveCompletedFromISR ENTER: xStreamBuffer 0x%08X, "
// >>RTOS_MAIN "pxHigherPriorityTaskWoken 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_RECEIVE_COMPLETED_FROM_ISR_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_RECEIVE_COMPLETED_FROM_ISR_RETURN 1678U
// >>RTOS_MAIN "%N %t xStreamBufferReceiveCompletedFromISR RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_STREAM_BUFFER_RECEIVE_COMPLETED_FROM_ISR_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_GET_NOTIFICATION_INDEX_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_GET_NOTIFICATION_INDEX_ENTER 1684U
// >>RTOS_MAIN "%N %t uxStreamBufferGetStreamBufferNotificationIndex ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_GET_NOTIFICATION_INDEX_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_GET_NOTIFICATION_INDEX_RETURN 1686U
// >>RTOS_MAIN "%N %t uxStreamBufferGetStreamBufferNotificationIndex RETURN: uxNotificationIndex %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_GET_NOTIFICATION_INDEX_ENTER](*1e6).3f us\n"

// MSG2_RTOS_STREAM_BUFFER_SET_NOTIFICATION_INDEX_ENTER ""
#define MSG2_RTOS_STREAM_BUFFER_SET_NOTIFICATION_INDEX_ENTER 1688U
// >>RTOS_MAIN "%N %t vStreamBufferSetStreamBufferNotificationIndex ENTER: xStreamBuffer 0x%08X, "
// >>RTOS_MAIN "uxNotificationIndex %u\n"

// MSG0_RTOS_STREAM_BUFFER_SET_NOTIFICATION_INDEX_RETURN ""
#define MSG0_RTOS_STREAM_BUFFER_SET_NOTIFICATION_INDEX_RETURN 1692U
// >>RTOS_MAIN "%N %t vStreamBufferSetStreamBufferNotificationIndex RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_STREAM_BUFFER_SET_NOTIFICATION_INDEX_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_GET_NUMBER_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_GET_NUMBER_ENTER 1694U
// >>RTOS_MAIN "%N %t uxStreamBufferGetStreamBufferNumber ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_GET_NUMBER_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_GET_NUMBER_RETURN 1696U
// >>RTOS_MAIN "%N %t uxStreamBufferGetStreamBufferNumber RETURN: uxStreamBufferNumber %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_GET_NUMBER_ENTER](*1e6).3f us\n"

// MSG2_RTOS_STREAM_BUFFER_SET_NUMBER_ENTER ""
#define MSG2_RTOS_STREAM_BUFFER_SET_NUMBER_ENTER 1700U
// >>RTOS_MAIN "%N %t vStreamBufferSetStreamBufferNumber ENTER: xStreamBuffer 0x%08X, "
// >>RTOS_MAIN "uxStreamBufferNumber %u\n"

// MSG0_RTOS_STREAM_BUFFER_SET_NUMBER_RETURN ""
#define MSG0_RTOS_STREAM_BUFFER_SET_NUMBER_RETURN 1693U
// >>RTOS_MAIN "%N %t vStreamBufferSetStreamBufferNumber RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_STREAM_BUFFER_SET_NUMBER_ENTER](*1e6).3f us\n"

// MSG1_RTOS_STREAM_BUFFER_GET_TYPE_ENTER ""
#define MSG1_RTOS_STREAM_BUFFER_GET_TYPE_ENTER 1698U
// >>RTOS_MAIN "%N %t ucStreamBufferGetStreamBufferType ENTER: xStreamBuffer 0x%08X\n"

// MSG1_RTOS_STREAM_BUFFER_GET_TYPE_RETURN ""
#define MSG1_RTOS_STREAM_BUFFER_GET_TYPE_RETURN 1704U
// >>RTOS_MAIN "%N %t ucStreamBufferGetStreamBufferType RETURN: ucStreamBufferType %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_STREAM_BUFFER_GET_TYPE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_LIST_INITIALISE_ENTER ""
#define MSG1_RTOS_LIST_INITIALISE_ENTER 1706U
// >>RTOS_MAIN "%N %t vListInitialise ENTER: pxList 0x%08X\n"

// MSG0_RTOS_LIST_INITIALISE_RETURN ""
#define MSG0_RTOS_LIST_INITIALISE_RETURN 1708U
// >>RTOS_MAIN "%N %t vListInitialise RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_LIST_INITIALISE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_LIST_INITIALISE_ITEM_ENTER ""
#define MSG1_RTOS_LIST_INITIALISE_ITEM_ENTER 1710U
// >>RTOS_MAIN "%N %t vListInitialiseItem ENTER: pxItem 0x%08X\n"

// MSG0_RTOS_LIST_INITIALISE_ITEM_RETURN ""
#define MSG0_RTOS_LIST_INITIALISE_ITEM_RETURN 1709U
// >>RTOS_MAIN "%N %t vListInitialiseItem RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_LIST_INITIALISE_ITEM_ENTER](*1e6).3f us\n"

// MSG2_RTOS_LIST_INSERT_END_ENTER ""
#define MSG2_RTOS_LIST_INSERT_END_ENTER 1712U
// >>RTOS_MAIN "%N %t vListInsertEnd ENTER: pxList 0x%08X, pxNewListItem 0x%08X\n"

// MSG0_RTOS_LIST_INSERT_END_RETURN ""
#define MSG0_RTOS_LIST_INSERT_END_RETURN 1716U
// >>RTOS_MAIN "%N %t vListInsertEnd RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_LIST_INSERT_END_ENTER](*1e6).3f us\n"

// MSG2_RTOS_LIST_INSERT_ENTER ""
#define MSG2_RTOS_LIST_INSERT_ENTER 1720U
// >>RTOS_MAIN "%N %t vListInsert ENTER: pxList 0x%08X, pxNewListItem 0x%08X\n"

// MSG0_RTOS_LIST_INSERT_RETURN ""
#define MSG0_RTOS_LIST_INSERT_RETURN 1717U
// >>RTOS_MAIN "%N %t vListInsert RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_LIST_INSERT_ENTER](*1e6).3f us\n"

// MSG1_RTOS_LIST_REMOVE_ENTER ""
#define MSG1_RTOS_LIST_REMOVE_ENTER 1718U
// >>RTOS_MAIN "%N %t uxListRemove ENTER: pxItemToRemove 0x%08X\n"

// MSG1_RTOS_LIST_REMOVE_RETURN ""
#define MSG1_RTOS_LIST_REMOVE_RETURN 1724U
// >>RTOS_MAIN "%N %t uxListRemove RETURN: uxNumberOfItems %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_LIST_REMOVE_ENTER](*1e6).3f us\n"

// MSG3_RTOS_CO_ROUTINE_CREATE_ENTER ""
#define MSG3_RTOS_CO_ROUTINE_CREATE_ENTER 1728U
// >>RTOS_MAIN "%N %t xCoRoutineCreate ENTER: pxCoRoutineCode 0x%08X, uxPriority %u, uxIndex %u\n"

// MSG1_RTOS_CO_ROUTINE_CREATE_RETURN ""
#define MSG1_RTOS_CO_ROUTINE_CREATE_RETURN 1726U
// >>RTOS_MAIN "%N %t xCoRoutineCreate RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG3_RTOS_CO_ROUTINE_CREATE_ENTER](*1e6).3f us\n"

// MSG2_RTOS_CO_ROUTINE_ADD_TO_DELAYED_LIST_ENTER ""
#define MSG2_RTOS_CO_ROUTINE_ADD_TO_DELAYED_LIST_ENTER 1736U
// >>RTOS_MAIN "%N %t vCoRoutineAddToDelayedList ENTER: xTicksToDelay %u, pxEventList 0x%08X\n"

// MSG0_RTOS_CO_ROUTINE_ADD_TO_DELAYED_LIST_RETURN ""
#define MSG0_RTOS_CO_ROUTINE_ADD_TO_DELAYED_LIST_RETURN 1740U
// >>RTOS_MAIN "%N %t vCoRoutineAddToDelayedList RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG2_RTOS_CO_ROUTINE_ADD_TO_DELAYED_LIST_ENTER](*1e6).3f us\n"

// MSG0_RTOS_CO_ROUTINE_SCHEDULE_ENTER ""
#define MSG0_RTOS_CO_ROUTINE_SCHEDULE_ENTER 1741U
// >>RTOS_MAIN "%N %t vCoRoutineSchedule ENTER\n"

// MSG0_RTOS_CO_ROUTINE_SCHEDULE_RETURN ""
#define MSG0_RTOS_CO_ROUTINE_SCHEDULE_RETURN 1742U
// >>RTOS_MAIN "%N %t vCoRoutineSchedule RETURN, "
// >>RTOS_MAIN "dt=%[t-MSG0_RTOS_CO_ROUTINE_SCHEDULE_ENTER](*1e6).3f us\n"

// MSG1_RTOS_CO_ROUTINE_REMOVE_FROM_EVENT_LIST_ENTER ""
#define MSG1_RTOS_CO_ROUTINE_REMOVE_FROM_EVENT_LIST_ENTER 1744U
// >>RTOS_MAIN "%N %t xCoRoutineRemoveFromEventList ENTER: pxEventList 0x%08X\n"

// MSG1_RTOS_CO_ROUTINE_REMOVE_FROM_EVENT_LIST_RETURN ""
#define MSG1_RTOS_CO_ROUTINE_REMOVE_FROM_EVENT_LIST_RETURN 1746U
// >>RTOS_MAIN "%N %t xCoRoutineRemoveFromEventList RETURN: xReturn %u, "
// >>RTOS_MAIN "dt=%[t-MSG1_RTOS_CO_ROUTINE_REMOVE_FROM_EVENT_LIST_ENTER](*1e6).3f us\n"

#endif
